---
title: "The Legacy of Eugenics in Statistics Pedagogy (Senior Thesis in Mathematics)"
date: "2025-5-5"
author: Emrys King
---

My senior thesis in mathematics, advised by [Jemma Lorenat](https://www.pitzer.edu/jemma-lorenat) and [Shahriar Shahriari](https://www.pomona.edu/directory/people/shahriar-shahriari), is titled *“Regression to the Mean”: The Confluence of Eugenics and Statistics in the 19th and 20th Centuries*. My research for this project was funded and supported by the [Humanities Studio](https://www.pomona.edu/administration/humanities-studio/about) Undergraduate Fellowship. Furthermore, my thesis earned [distinction](https://catalog.pomona.edu/programs/0koJCGUpGYx3LPFrBGss#:~:text=To%20be%20considered,coherent%20intellectual%20organization.) from the Department of Mathematics and Statistics at Pomona College. I have included my data analysis and visualization chapter below. The full thesis is available through an open-access license [here](https://scholarship.claremont.edu/pomona_theses/347/).

**Abstract:** The work of this thesis is twofold — first, qualitatively characterizing the confluence between the British eugenics and statistics movements in the late 19th and early 20th centuries, and second, quantitatively analyzing the effect of this foundation on pedagogical materials in the growing field of statistics between 1880 and 1970. Towards the first goal, the history of the method of least squares, state statistics, and positive and negative eugenics are outlined, followed by a close reading of the foundational texts authored by Francis Galton and Karl Pearson that introduced linear regression. Towards the latter goal, English-language statistics textbooks published between 1880 and 1970 are analyzed using text-mining algorithms to establish the extent of their co-existence with hereditary and eugenic studies.


{{< pdf thesis.pdf width=80% height=750 border=1 >}}
