<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Emrys King and Marissa Douglas">
<meta name="dcterms.date" content="2024-12-06">

<title>Prediction of Life Expectancy and its Relationship to GDP – Emrys King</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../logo.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-052dd319b41bb23bc4502c5e2ea7d85c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="../site_libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">
<script src="../site_libs/tabwid-1.1.3/tabwid.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../logo.png" alt="A hypercube logo." class="navbar-logo light-content">
    <img src="../logo.png" alt="A hypercube logo." class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Emrys King</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text"> </span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../cv.html"> 
<span class="menu-text">CV</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data-set" id="toc-data-set" class="nav-link" data-scroll-target="#data-set">Data Set</a></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis">Analysis</a>
  <ul class="collapse">
  <li><a href="#exploratory-analysis" id="toc-exploratory-analysis" class="nav-link" data-scroll-target="#exploratory-analysis">Exploratory Analysis</a></li>
  <li><a href="#preliminary-models" id="toc-preliminary-models" class="nav-link" data-scroll-target="#preliminary-models">Preliminary Models</a></li>
  <li><a href="#model-diagnostics" id="toc-model-diagnostics" class="nav-link" data-scroll-target="#model-diagnostics">Model Diagnostics</a></li>
  <li><a href="#influential-points" id="toc-influential-points" class="nav-link" data-scroll-target="#influential-points">Influential Points</a></li>
  <li><a href="#transformations" id="toc-transformations" class="nav-link" data-scroll-target="#transformations">Transformations</a></li>
  <li><a href="#collinearity" id="toc-collinearity" class="nav-link" data-scroll-target="#collinearity">Collinearity</a></li>
  <li><a href="#model-selection" id="toc-model-selection" class="nav-link" data-scroll-target="#model-selection">Model Selection</a></li>
  <li><a href="#shrinkage-methods" id="toc-shrinkage-methods" class="nav-link" data-scroll-target="#shrinkage-methods">Shrinkage Methods</a></li>
  <li><a href="#anova" id="toc-anova" class="nav-link" data-scroll-target="#anova">ANOVA</a></li>
  </ul></li>
  <li><a href="#results-and-conclusions" id="toc-results-and-conclusions" class="nav-link" data-scroll-target="#results-and-conclusions">Results and Conclusions</a>
  <ul class="collapse">
  <li><a href="#results-evaluating-model-performance" id="toc-results-evaluating-model-performance" class="nav-link" data-scroll-target="#results-evaluating-model-performance">Results: Evaluating Model Performance</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Prediction of Life Expectancy and its Relationship to GDP</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Emrys King and Marissa Douglas </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 6, 2024</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    In this report, we first seek to analyze the relationship between the Gross Domestic Product (GDP) per capita of a country and the life expectancy of that country’s citizens. Using data from the World Health Organization (WHO) on several measures of health, economic status, and geopolitical status, we build explanatory linear regression models and compare the presence of GDP per capita in each of these. Secondarily, we seek to build the optimal model for prediction of life expectancy using the same measures. We employ simple and multiple linear regression, Box-Cox transformation, and shrinkage methods, identify influential points in the model fit, run Box-Cox transformation computations, assess the presence of collinearity, use stepwise elimination to select optimal predictors, and consider the prediction of life expectancy by categorical variables using ANOVA. We conclude by comparing each model across multiple measures of performance and their adherence to the assumptions of homoskedasticity and normality.
  </div>
</div>


</header>


<div style="page-break-after: always;"></div>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>GDP per capita is a measurement of the share of GDP per person, which is calculated by summing the consumption, investments, and exports of a country, subtracting the imports, and dividing this value by the population of that country. GDP is a strong economic estimate of the wealth and living standards of a country, but is not enough to describe the income distribution of a country and individual economic reality. As such, we are curious if GDP per capita is a good indicator of the health of a country, as measured by life expectancy, or if GDP per capita falls short in describing country health. To answer this question, we will build a linear regression model with life expectancy as the response variables and all other eligible variables as predictors.</p>
<p>On a secondary level, we are interested in creating an optimal tool for predicting life expectancy, without regard for the explanatory power of each predictor variable. To consider all possibilities in building this tool, we will include different shrinkage methods. Principal component regression, partial least squares regression, and ridge regression will be employed and evaluated via the root mean squared error, as will more standard models. The limitations of all models will be discussed alongside their benefits.</p>
</section>
<section id="data-set" class="level1">
<h1>Data Set</h1>
<p>We have obtained an updated version of the World Health Organization’s (WHO) data from 2000-2015 on the life expectancy, health, immunization, and economic and demographic information of 179 different countries. The updated version of the data resolved missing data issues and includes additional columns about income. This data is sourced from Gochiashvili (2023) on Kaggle (https://www.kaggle.com/datasets/lashagoch/life-expectancy-who-updated).</p>
<p>Here we include a description of the variables in the dataset.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-6d449f48{}.cl-6d3b4736{font-family:'Arial';font-size:10pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-6d40922c{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-6d40b05e{width:2.146in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6d40b068{width:3in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6d40b069{width:2.146in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6d40b072{width:3in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6d40b07c{width:2.146in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6d40b086{width:3in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6d40b090{width:2.146in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6d40b091{width:3in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6d40b09a{width:2.146in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6d40b09b{width:3in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6d40b0ae{width:2.146in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6d40b0af{width:3in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6d40b0b0{width:2.146in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6d40b0b8{width:3in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6d40b0c2{width:2.146in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6d40b0c3{width:3in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-6d449f48"><thead><tr style="overflow-wrap:break-word;"><th class="cl-6d40b05e"><p class="cl-6d40922c"><span class="cl-6d3b4736">Variable</span></p></th><th class="cl-6d40b068"><p class="cl-6d40922c"><span class="cl-6d3b4736">Description</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-6d40b069"><p class="cl-6d40922c"><span class="cl-6d3b4736">Country</span></p></td><td class="cl-6d40b072"><p class="cl-6d40922c"><span class="cl-6d3b4736">List of the 179 countries</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6d40b07c"><p class="cl-6d40922c"><span class="cl-6d3b4736">Region</span></p></td><td class="cl-6d40b086"><p class="cl-6d40922c"><span class="cl-6d3b4736">179 countries are distributed in 9 regions. E.g. Africa, Asia, Oceania, European Union, Rest of Europe and etc.</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6d40b090"><p class="cl-6d40922c"><span class="cl-6d3b4736">Year</span></p></td><td class="cl-6d40b091"><p class="cl-6d40922c"><span class="cl-6d3b4736">Years observed from 2000 to 2015</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6d40b09a"><p class="cl-6d40922c"><span class="cl-6d3b4736">Infant_deaths</span></p></td><td class="cl-6d40b09b"><p class="cl-6d40922c"><span class="cl-6d3b4736">Infant deaths per 1000 population</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6d40b069"><p class="cl-6d40922c"><span class="cl-6d3b4736">Under_five_deaths</span></p></td><td class="cl-6d40b072"><p class="cl-6d40922c"><span class="cl-6d3b4736">Deaths of children under five years old per 1000 population</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6d40b09a"><p class="cl-6d40922c"><span class="cl-6d3b4736">Adult_mortality</span></p></td><td class="cl-6d40b09b"><p class="cl-6d40922c"><span class="cl-6d3b4736">Deaths of adults per 1000 population</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6d40b069"><p class="cl-6d40922c"><span class="cl-6d3b4736">Alcohol_consumption</span></p></td><td class="cl-6d40b072"><p class="cl-6d40922c"><span class="cl-6d3b4736">Alcohol consumption, recorded in liters of pure alcohol per capita (15+ years old)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6d40b069"><p class="cl-6d40922c"><span class="cl-6d3b4736">Hepatitis_B</span></p></td><td class="cl-6d40b072"><p class="cl-6d40922c"><span class="cl-6d3b4736">Percent coverage of Hepatitis B (HepB3) immunization among 1-year-olds.</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6d40b069"><p class="cl-6d40922c"><span class="cl-6d3b4736">Measles</span></p></td><td class="cl-6d40b072"><p class="cl-6d40922c"><span class="cl-6d3b4736">Percent coverage of Measles containing vaccine first dose (MCV1) immunization among 1-year-olds</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6d40b069"><p class="cl-6d40922c"><span class="cl-6d3b4736">BMI</span></p></td><td class="cl-6d40b072"><p class="cl-6d40922c"><span class="cl-6d3b4736">A measure of nutritional status in adults, defined as a person’s weight in kilograms divided by the square of that person’s height in meters (kg/m2)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6d40b069"><p class="cl-6d40922c"><span class="cl-6d3b4736">Polio</span></p></td><td class="cl-6d40b072"><p class="cl-6d40922c"><span class="cl-6d3b4736">Percent coverage of Polio (Pol3) immunization among 1-year-olds.</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6d40b069"><p class="cl-6d40922c"><span class="cl-6d3b4736">Diphtheria</span></p></td><td class="cl-6d40b072"><p class="cl-6d40922c"><span class="cl-6d3b4736">Percent coverage of Diphtheria tetanus toxoid and pertussis (DTP3) immunization among 1-year-olds.</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6d40b069"><p class="cl-6d40922c"><span class="cl-6d3b4736">Incidents_HIV</span></p></td><td class="cl-6d40b072"><p class="cl-6d40922c"><span class="cl-6d3b4736">Incidence of HIV, measured in cases per 1000 population aged 15-49</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6d40b069"><p class="cl-6d40922c"><span class="cl-6d3b4736">GDP_per_capita</span></p></td><td class="cl-6d40b072"><p class="cl-6d40922c"><span class="cl-6d3b4736">GDP per capita in current United States Dollars (USD)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6d40b0ae"><p class="cl-6d40922c"><span class="cl-6d3b4736">Population_mln</span></p></td><td class="cl-6d40b0af"><p class="cl-6d40922c"><span class="cl-6d3b4736">Total population in millions</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6d40b069"><p class="cl-6d40922c"><span class="cl-6d3b4736">Thinness_ten_nineteen_years</span></p></td><td class="cl-6d40b072"><p class="cl-6d40922c"><span class="cl-6d3b4736">Prevalence of thinness among adolescents aged 10-19 years. BMI &lt; -2 standard deviations below the median.</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6d40b069"><p class="cl-6d40922c"><span class="cl-6d3b4736">Thinness_five_nine_years</span></p></td><td class="cl-6d40b072"><p class="cl-6d40922c"><span class="cl-6d3b4736">Prevalence of thinness among children aged 5-9 years. BMI &lt; -2 standard deviations below the median.</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6d40b069"><p class="cl-6d40922c"><span class="cl-6d3b4736">Schooling</span></p></td><td class="cl-6d40b072"><p class="cl-6d40922c"><span class="cl-6d3b4736">Average years that people aged 25+ spent in formal education</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6d40b0b0"><p class="cl-6d40922c"><span class="cl-6d3b4736">Economy_status_Developed</span></p></td><td class="cl-6d40b0b8"><p class="cl-6d40922c"><span class="cl-6d3b4736">Binary variable. 0=Developing country, 1=Developed country.</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6d40b0b0"><p class="cl-6d40922c"><span class="cl-6d3b4736">Economy_status_Developing</span></p></td><td class="cl-6d40b0b8"><p class="cl-6d40922c"><span class="cl-6d3b4736">Binary variable. 0=Developed country, 1=Developing country.</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6d40b0c2"><p class="cl-6d40922c"><span class="cl-6d3b4736">Life_expectancy</span></p></td><td class="cl-6d40b0c3"><p class="cl-6d40922c"><span class="cl-6d3b4736">Average life expectancy of both genders in the given year</span></p></td></tr></tbody></table></div>
</div>
</div>
</section>
<section id="analysis" class="level1">
<h1>Analysis</h1>
<section id="exploratory-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-analysis">Exploratory Analysis</h2>
<p>To better understand our data, we began with an exploratory analysis. We first observe that the dataset is a time series. Thus, to avoid possible autocorrelations of variables, we have limited our observations for analysis to the year 2015. This year has 179 observations, each corresponding to a different country. To test the predictive capability within the same year, we have reserved 20% of the data (every 5th observation) for use as a test dataset, while the remaining observations will be used to train the models.</p>
<p>We first plotted the raw relationship between GDP per capita and life expectancy in 2015. Though we removed 20% of the data to use as test cases, the overall shape of the data does not change. In this plot, we observe a positive relationship between GDP per capita and Life Expectancy, and this relationship appears non-linear. Most likely, it is logarithmic. We will test the assumptions on an ordinary least squares regression and inform our analysis from there.</p>
<p>Furthermore, we have colored each datapoint by region to show general geographical trends, which reflect the histories of different regions, including how wars and exploitation of regions in the Global South have impacted economies. Most interesting about this spread is that we see high levels of within-group variation. For example, the datapoints for Africa have near 0 GDP per capita, but their life expectancies range across the vertical axis. Conversely, the datapoints for the European Union have life expectancies near 80, but GDP per capita that range across the horizontal axis. We will analyze this phenomenon further using Analysis of Variance (ANOVA) in a later section.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="SLMFinal_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Following this initial graph, we would like to see other relationships between variables in the dataset. We look at a years of schooling vs.&nbsp;GDP per capita plot to understand if other similar relationships exist between GDP per capita and status metrics.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="SLMFinal_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>We see a similar nonlinear (likely logarithmic) trend in the plot of years of schooling against GDP per capita. This plot also contains the same within-group variation phenomenon as above. Thus, we expect that there is likely a linear relationship between life expectancy and years of schooling. We observe this relationship below.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="SLMFinal_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>We do see a linear relationship, with a low signal-to-noise. Thus, while a model predicting life expectancy with only GDP per capita would likely require a transformation of the response, a model predicting life expectancy with only years of schooling would likely not need such a transformation.</p>
<p>To finish our exploratory data analysis, we note that there is a high likelihood of collinearity between predictor variables in this dataset. For example, the predictors related to rates of immunization coverage are likely collinear due to the fact that several immunizations may given to a child in one sitting. We investigate one such possible collinearity in the plots below, which show every possible combination of the four vaccine coverage variables (percent coverage of Hepatitis B vaccination, percent coverage of Measles vaccination, percent coverage of Polio vaccination, percent coverage of Diphtheria vaccination)</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="SLMFinal_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>While some plots have a clearer linear relationship than others, and there is definitely a ceiling effect occurring, there seems to be some degree of linearity present between each pair of immunizations. We will investigate collinearity more rigorously in a later section.</p>
</section>
<section id="preliminary-models" class="level2">
<h2 class="anchored" data-anchor-id="preliminary-models">Preliminary Models</h2>
<p>We begin our data analysis with a multiple linear regression model. We use all possible predictors to model life expectancy, and fit the model using the ordinary method of least squares. For conciseness, we will refer to this model as the Full OLS model. Below is displayed a summary of the Full OLS model.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Life_expectancy ~ Region + Infant_deaths + Under_five_deaths + 
    Adult_mortality + Alcohol_consumption + Hepatitis_B + Measles + 
    BMI + Polio + Diphtheria + Incidents_HIV + GDP_per_capita + 
    Population_mln + Thinness_ten_nineteen_years + Thinness_five_nine_years + 
    Schooling + Economy_status_Developing, data = train_lifeexp)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.3525 -0.8608  0.0120  0.7495  3.2817 

Coefficients:
                                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                          8.696e+01  2.702e+00  32.189  &lt; 2e-16 ***
RegionAsia                           2.434e-01  4.780e-01   0.509  0.61165    
RegionCentral America and Caribbean  1.451e+00  5.163e-01   2.809  0.00581 ** 
RegionEuropean Union                -7.813e-01  7.436e-01  -1.051  0.29554    
RegionMiddle East                    4.371e-01  5.918e-01   0.739  0.46161    
RegionNorth America                  1.701e-01  1.132e+00   0.150  0.88085    
RegionOceania                       -1.322e+00  6.436e-01  -2.054  0.04213 *  
RegionRest of Europe                 2.680e-01  5.926e-01   0.452  0.65195    
RegionSouth America                  1.810e+00  5.747e-01   3.149  0.00207 ** 
Infant_deaths                       -6.433e-02  4.785e-02  -1.344  0.18135    
Under_five_deaths                   -4.827e-02  3.123e-02  -1.546  0.12486    
Adult_mortality                     -4.791e-02  3.286e-03 -14.581  &lt; 2e-16 ***
Alcohol_consumption                 -2.773e-02  5.413e-02  -0.512  0.60942    
Hepatitis_B                         -1.463e-02  2.710e-02  -0.540  0.59039    
Measles                              9.839e-03  9.000e-03   1.093  0.27651    
BMI                                 -1.195e-01  9.229e-02  -1.295  0.19789    
Polio                                3.358e-03  2.556e-02   0.131  0.89570    
Diphtheria                           1.380e-02  3.092e-02   0.446  0.65625    
Incidents_HIV                        2.013e-01  9.216e-02   2.184  0.03093 *  
GDP_per_capita                       2.619e-05  9.277e-06   2.824  0.00557 ** 
Population_mln                      -3.914e-05  7.186e-04  -0.054  0.95666    
Thinness_ten_nineteen_years         -2.794e-01  1.571e-01  -1.779  0.07785 .  
Thinness_five_nine_years             2.392e-01  1.568e-01   1.525  0.12990    
Schooling                           -4.204e-02  8.480e-02  -0.496  0.62104    
Economy_status_Developing           -3.129e+00  7.253e-01  -4.314 3.33e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.225 on 119 degrees of freedom
Multiple R-squared:  0.9798,    Adjusted R-squared:  0.9758 
F-statistic: 240.8 on 24 and 119 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>There are a few key takeaways from this summary. First, the standard errors are very small, with the largest being 2.702 (associated with the <code>(Intercept)</code> term). This indicates that the fitted linear relationship is a very good approximation of the actual relationship between the datapoints, which is corroborated by the very high value of <span class="math inline">\(R^2=0.9798\)</span>. However, this excellent fit is accompanied by only a few significant predictors: <code>RegionCentral America and Caribbean</code>, <code>RegionOceania</code>, <code>RegionSouth America</code>, <code>Adult_mortality</code>, <code>Incidents_HIV</code>, <code>GDP_per_capita</code>, and <code>Economy_status_Developing</code> (out of 24 total predictors). This is a definite symptom of collinearity. We will address collinearity more fully in a later section.</p>
<p>In regards to the first goal of this analysis, we see that, while GDP per capita is a significant predictor of life expectancy, it is not the only significant predictor. We thus compare the above model to the simple linear regression model with life expectancy as the response and GDP per capita as the sole predictor. First, let us observe a summary of the simple linear regression model.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Life_expectancy ~ GDP_per_capita, data = train_lifeexp)

Residuals:
    Min      1Q  Median      3Q     Max 
-17.585  -3.296   1.542   4.465   8.672 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    6.828e+01  6.355e-01 107.445   &lt;2e-16 ***
GDP_per_capita 2.648e-04  2.743e-05   9.653   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.133 on 142 degrees of freedom
Multiple R-squared:  0.3962,    Adjusted R-squared:  0.3919 
F-statistic: 93.18 on 1 and 142 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>While the standard errors are still small and the predictor significant, the <span class="math inline">\(R^2\)</span> value has decreased greatly to 0.3962. Since the predictor of the simple linear regression (SLR) model is a subset of predictors of the Full OLS model, we may use the nested model hypothesis test to evaluate the significance of the difference between the two models. The nested model hypothesis test for our current models is as follows: <span class="math display">\[\begin{cases} H_0:&amp; \textrm{the SLR and Full OLS models have equivalent levels of accuracy} \\ H_a:&amp; \textrm{the larger Full OLS model is more accurate than the SLR model} \end{cases}\]</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="huxtable" data-quarto-disable-processing="true" style="margin-left: auto; margin-right: auto;" id="tab:Nested Model Testing">
<colgroup><col><col><col><col><col><col></colgroup><thead>
<tr>
<th class="huxtable-cell huxtable-header" style="text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0.4pt;">Res.Df</th><th class="huxtable-cell huxtable-header" style="text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;">RSS</th><th class="huxtable-cell huxtable-header" style="text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;">Df</th><th class="huxtable-cell huxtable-header" style="text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;">Sum of Sq</th><th class="huxtable-cell huxtable-header" style="text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;">F</th><th class="huxtable-cell huxtable-header" style="text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0.4pt 0pt;">Pr(&gt;F)</th></tr>
</thead>
<tbody>
<tr>
<td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0.4pt;     background-color: rgb(242, 242, 242);">119</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;     background-color: rgb(242, 242, 242);">178&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;     background-color: rgb(242, 242, 242);"></td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;     background-color: rgb(242, 242, 242);">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;     background-color: rgb(242, 242, 242);"></td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0pt 0pt;     background-color: rgb(242, 242, 242);">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0.4pt;">142</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;">5.34e+03</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;">-23</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;">-5.16e+03</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;">150</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0.4pt 0.4pt 0pt;">9.82e-77</td></tr>
</tbody>
</table>
</div>
</div>
<p>Since the <span class="math inline">\(p\)</span>-value is less than 0.05, we reject the null hypothesis. Therefore, without any transformation or other considerations like model diagnostics, the Full OLS model is less accurate than the SLR model.</p>
</section>
<section id="model-diagnostics" class="level2">
<h2 class="anchored" data-anchor-id="model-diagnostics">Model Diagnostics</h2>
<p>An important consideration in building linear regression models using ordinary least squares is the adherence of the model to certain assumptions. In particular, one must assure that the residuals (the distance between the fitted values and actual datapoints) have constant variance — also called homoskedasticity — and that the distribution of the residuals is normal. To evaluate these assumptions, we have written a function, <code>diagnostics()</code>, which takes a linear model as input and returns two plots and two tests to assess the assumptions. The first plot, fitted vs.&nbsp;residuals, gives a visual representation of the variance of the residuals, which can be used to understand if the variance is constant. We include the line <span class="math inline">\(y=0\)</span>, towards which the residuals are minimized, to observe if they are evenly and randomly distributed on either side of the line. This plot corresponds with the output of the non-constant variance test. The second plot, the Normal Q-Q plot, displays the sample vs.&nbsp;theoretical quantiles of the residuals. If these quantiles are equal, then the residuals will be perfectly normal; thus, in this plot, we look for adherence to the line <span class="math inline">\(y=x\)</span>. This plot corresponds with the output of the Shapiro-Wilks test of normality.</p>
<p>Below we see the output of the <code>diagnostics()</code> function for the Full OLS model.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="SLMFinal_files/figure-html/Full OLS diagnostics-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="SLMFinal_files/figure-html/Full OLS diagnostics-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Non-constant Variance Score Test 
Variance formula: ~ fitted.values 
Chisquare = 4.692216, Df = 1, p = 0.0303

    Shapiro-Wilk normality test

data:  resid(lm)
W = 0.98961, p-value = 0.3632</code></pre>
</div>
</div>
<p>The Full OLS model breaks the homoskedasticity assumption. This can be seen in the leftmost tail of the residuals vs.&nbsp;fitted plot above: on the interval of fitted values [50, 57], nearly all of the residuals are positive, so even though the rest of the plot seems randomly distributed across positive and negative, the overall variance cannot be constant. We confirm this result by the <span class="math inline">\(p\)</span>-value of the non-constant variance test, <span class="math inline">\(p=0.0303&lt;0.05\)</span>, which allows us to reject the null hypothesis of homoskedasticity.</p>
<p>Since the variance is non-constant, the residuals cannot be truly normally distributed. However, the Q-Q plot above shows a good adherence to the line and the Shapiro-Wilks test returns a <span class="math inline">\(p\)</span>-value of <span class="math inline">\(p=0.3632&gt;0.05\)</span>, meaning we fail to reject the null hypothesis of normality. Thus, though the residuals are heteroskedastic, we may view them as approximately normally distributed.</p>
<p>We can also view the diagnostic output for the SLR model.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="SLMFinal_files/figure-html/SLR diagnostics-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="SLMFinal_files/figure-html/SLR diagnostics-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Non-constant Variance Score Test 
Variance formula: ~ fitted.values 
Chisquare = 1.433745, Df = 1, p = 0.23115

    Shapiro-Wilk normality test

data:  resid(lm)
W = 0.9175, p-value = 2.36e-07</code></pre>
</div>
</div>
<p>The most egregious violation of the assumptions above is the violation of normality. With <span class="math inline">\(p=2.36e-07\)</span> in the Shapiro-Wilks test, we can soundly reject the null hypothesis of normality, corroborated visually by the non-equivalence of the quantiles in the Q-Q plot.</p>
<p>If normality is assumed, however, the variance is constant: there is an equivalent proportion of negative and positive residuals. The nonconstant variance test <span class="math inline">\(p\)</span>-value, <span class="math inline">\(p=0.23115\)</span>, agrees with this statement. However, since the residuals are clearly not randomly distributed, homoskedasticity is a bit of a moot point.</p>
<p>Thus, in terms of assumptions, the Full OLS model once again trumps the SLR model. In the following sections, further models will be built to attempt to resolve the Full OLS model’s violation of assumptions.</p>
</section>
<section id="influential-points" class="level2">
<h2 class="anchored" data-anchor-id="influential-points">Influential Points</h2>
<p>In order to apply transformations to the response variable, assess collinearity, and later on run shrinkage methods, one should first analyze the presence and location of influential points in the dataset. Influential points can drastically change the fit of a model. Box-Cox transformations and shrinkage methods are sensitive to influential points, and thus their removal can give a more accurate treatment of the data.</p>
<p>Similarly to the above section, we wrote a function, <code>unusual_obs()</code>, which will identify all points of high leverage, outlier points, and influential points. A point with high leverage is defined as one whose leverage is twice the mean leverage in a given dataset. In turn, leverage is given as the diagonals of the hat matrix <span class="math inline">\(H=X(X^TX)^{-1}X^T\)</span>. Points with high leverage may potentially have a big impact on the fit of the model, but only if they are outliers as well. Outliers are points that do not fit the model well. To find outliers, we locate all datapoints whose standardized residuals are greater than 2 or less than <span class="math inline">\(-2\)</span>. Finally, we find the influential points by calculating the Cook’s distance of each point identified as either a point of high leverage or an outlier. If the Cook’s distance <span class="math inline">\(D_i\)</span> of any of these points is greater than <span class="math inline">\(\frac{4}{n}\)</span> (<span class="math inline">\(n\)</span> being the sample size), then we heuristically consider those points influential.</p>
<p>Below we identify the outliers for the Full OLS model.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Large Leverage"
        9        15        23        25        31        33        37        68 
0.5297997 0.3730873 0.3950965 0.6157479 0.6516889 0.6157479 0.6404849 0.4419994 
      106       128 
0.3872335 0.9594019 
[1] "Outliers"
        9        14        46        53       107 
-2.513456 -2.032598  3.073952  2.291787  2.029910 
[1] "Influential Points"
    9    15    23    25    31    33    37    68   106   128 
 TRUE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE  TRUE 
    9    14    46    53   107 
 TRUE FALSE  TRUE  TRUE  TRUE </code></pre>
</div>
</div>
<p>Thus, we have influential points at observations 9, 31, 128 (which have high leverage), and 46, 53, 107 (which are outliers). Let’s see which points these are.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-6e88c668{}.cl-6e821782{font-family:'Arial';font-size:10pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-6e84ab14{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-6e84ab1e{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-6e84c766{width:1.08in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e84c770{width:0.725in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e84c771{width:1.289in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e84c77a{width:1.312in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e84c77b{width:1.08in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e84c784{width:0.725in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e84c785{width:1.289in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e84c78e{width:1.312in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e84c798{width:1.08in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e84c799{width:0.725in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e84c7a2{width:1.289in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e84c7ac{width:1.312in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e84c7ad{width:1.08in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e84c7b6{width:0.725in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e84c7b7{width:1.289in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e84c7c0{width:1.312in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e84c7c1{width:1.08in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e84c7ca{width:0.725in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e84c7cb{width:1.289in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e84c7d4{width:1.312in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e84c7de{width:1.08in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e84c7e8{width:0.725in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e84c7f2{width:1.289in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e84c7f3{width:1.312in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-6e88c668"><thead><tr style="overflow-wrap:break-word;"><th class="cl-6e84c766"><p class="cl-6e84ab14"><span class="cl-6e821782">Country</span></p></th><th class="cl-6e84c770"><p class="cl-6e84ab14"><span class="cl-6e821782">Region</span></p></th><th class="cl-6e84c771"><p class="cl-6e84ab1e"><span class="cl-6e821782">Life_expectancy</span></p></th><th class="cl-6e84c77a"><p class="cl-6e84ab1e"><span class="cl-6e821782">GDP_per_capita</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-6e84c77b"><p class="cl-6e84ab14"><span class="cl-6e821782">Eswatini</span></p></td><td class="cl-6e84c784"><p class="cl-6e84ab14"><span class="cl-6e821782">Africa</span></p></td><td class="cl-6e84c785"><p class="cl-6e84ab1e"><span class="cl-6e821782">55.4</span></p></td><td class="cl-6e84c78e"><p class="cl-6e84ab1e"><span class="cl-6e821782">3680</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6e84c798"><p class="cl-6e84ab14"><span class="cl-6e821782">China</span></p></td><td class="cl-6e84c799"><p class="cl-6e84ab14"><span class="cl-6e821782">Asia</span></p></td><td class="cl-6e84c7a2"><p class="cl-6e84ab1e"><span class="cl-6e821782">75.9</span></p></td><td class="cl-6e84c7ac"><p class="cl-6e84ab1e"><span class="cl-6e821782">8016</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6e84c7ad"><p class="cl-6e84ab14"><span class="cl-6e821782">Philippines</span></p></td><td class="cl-6e84c7b6"><p class="cl-6e84ab14"><span class="cl-6e821782">Asia</span></p></td><td class="cl-6e84c7b7"><p class="cl-6e84ab1e"><span class="cl-6e821782">70.6</span></p></td><td class="cl-6e84c7c0"><p class="cl-6e84ab1e"><span class="cl-6e821782">3001</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6e84c798"><p class="cl-6e84ab14"><span class="cl-6e821782">Sierra Leone</span></p></td><td class="cl-6e84c799"><p class="cl-6e84ab14"><span class="cl-6e821782">Africa</span></p></td><td class="cl-6e84c7a2"><p class="cl-6e84ab1e"><span class="cl-6e821782">52.9</span></p></td><td class="cl-6e84c7ac"><p class="cl-6e84ab1e"><span class="cl-6e821782">588</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6e84c7c1"><p class="cl-6e84ab14"><span class="cl-6e821782">Thailand</span></p></td><td class="cl-6e84c7ca"><p class="cl-6e84ab14"><span class="cl-6e821782">Asia</span></p></td><td class="cl-6e84c7cb"><p class="cl-6e84ab1e"><span class="cl-6e821782">76.1</span></p></td><td class="cl-6e84c7d4"><p class="cl-6e84ab1e"><span class="cl-6e821782">5840</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6e84c7de"><p class="cl-6e84ab14"><span class="cl-6e821782">Singapore</span></p></td><td class="cl-6e84c7e8"><p class="cl-6e84ab14"><span class="cl-6e821782">Asia</span></p></td><td class="cl-6e84c7f2"><p class="cl-6e84ab1e"><span class="cl-6e821782">82.7</span></p></td><td class="cl-6e84c7f3"><p class="cl-6e84ab1e"><span class="cl-6e821782">55647</span></p></td></tr></tbody></table></div>
</div>
</div>
<p>We see that all of the influential points are in Africa and Asia. To compare these to their regions in particular, and to account for possible socioeconomic factors, we observe the regional mean and standard deviation for GDP per capita in Asia and Africa in 2015.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-6e9e91f0{}.cl-6e966a8e{font-family:'Arial';font-size:10pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-6e99965a{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-6e999678{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-6e99b6ee{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e99b6f8{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e99b702{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e99b70c{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e99b70d{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6e99b716{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-6e9e91f0"><thead><tr style="overflow-wrap:break-word;"><th class="cl-6e99b6ee"><p class="cl-6e99965a"><span class="cl-6e966a8e">Region</span></p></th><th class="cl-6e99b6f8"><p class="cl-6e999678"><span class="cl-6e966a8e">Mean</span></p></th><th class="cl-6e99b6f8"><p class="cl-6e999678"><span class="cl-6e966a8e">Standard.Dev</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-6e99b702"><p class="cl-6e99965a"><span class="cl-6e966a8e">Asia</span></p></td><td class="cl-6e99b70c"><p class="cl-6e999678"><span class="cl-6e966a8e">7832.185</span></p></td><td class="cl-6e99b70c"><p class="cl-6e999678"><span class="cl-6e966a8e">12684.597</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6e99b70d"><p class="cl-6e99965a"><span class="cl-6e966a8e">Africa</span></p></td><td class="cl-6e99b716"><p class="cl-6e999678"><span class="cl-6e966a8e">2704.980</span></p></td><td class="cl-6e99b716"><p class="cl-6e999678"><span class="cl-6e966a8e">3182.277</span></p></td></tr></tbody></table></div>
</div>
</div>
<p>Almost all of the outliers are within one standard deviation of the mean GDP per capita of their region, except Singapore. We also note that the mean GDP per capita across all regions in 2015 was $12617.3, while the standard deviation was $17719.61; thus, all outliers except Singapore were also within one standard deviation of the overall mean. Therefore, we arrive at another piece of evidence in support of the claim that GDP per capita is not the most accurate or significant predictor of life expectancy.</p>
<p>Having qualitatively and quantitatively assessed the nature of the outlier datapoints, we now remove them from the training dataset, since shrinkage methods are very particular about outliers. We then refit the Full OLS model without outliers.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Life_expectancy ~ Region + Infant_deaths + Under_five_deaths + 
    Adult_mortality + Alcohol_consumption + Hepatitis_B + Measles + 
    BMI + Polio + Diphtheria + Incidents_HIV + GDP_per_capita + 
    Population_mln + Thinness_ten_nineteen_years + Thinness_five_nine_years + 
    Schooling + Economy_status_Developing, data = train_lifeexp_clean)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.12070 -0.79788  0.04188  0.68388  2.77214 

Coefficients:
                                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                          8.864e+01  2.599e+00  34.106  &lt; 2e-16 ***
RegionAsia                           2.006e-01  4.626e-01   0.434 0.665444    
RegionCentral America and Caribbean  1.403e+00  4.705e-01   2.982 0.003508 ** 
RegionEuropean Union                -1.062e+00  6.840e-01  -1.553 0.123259    
RegionMiddle East                    4.894e-01  5.422e-01   0.903 0.368619    
RegionNorth America                 -2.740e-01  1.026e+00  -0.267 0.789833    
RegionOceania                       -1.518e+00  5.851e-01  -2.594 0.010755 *  
RegionRest of Europe                 1.442e-01  5.574e-01   0.259 0.796264    
RegionSouth America                  1.804e+00  5.257e-01   3.432 0.000838 ***
Infant_deaths                       -9.166e-02  4.450e-02  -2.060 0.041689 *  
Under_five_deaths                   -4.017e-02  2.880e-02  -1.395 0.165786    
Adult_mortality                     -4.880e-02  2.972e-03 -16.423  &lt; 2e-16 ***
Alcohol_consumption                 -4.457e-02  5.020e-02  -0.888 0.376519    
Hepatitis_B                         -2.009e-02  2.450e-02  -0.820 0.414035    
Measles                              1.644e-02  8.427e-03   1.951 0.053552 .  
BMI                                 -9.165e-02  8.721e-02  -1.051 0.295550    
Polio                               -1.672e-02  2.382e-02  -0.702 0.484324    
Diphtheria                           2.657e-02  2.824e-02   0.941 0.348874    
Incidents_HIV                        4.374e-01  1.088e-01   4.020 0.000105 ***
GDP_per_capita                       2.013e-05  8.703e-06   2.313 0.022523 *  
Population_mln                       1.240e-03  1.013e-03   1.224 0.223483    
Thinness_ten_nineteen_years         -9.414e-01  6.477e-01  -1.453 0.148890    
Thinness_five_nine_years             8.650e-01  6.349e-01   1.362 0.175783    
Schooling                           -1.244e-01  8.209e-02  -1.515 0.132476    
Economy_status_Developing           -3.593e+00  6.760e-01  -5.316 5.41e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.099 on 113 degrees of freedom
Multiple R-squared:  0.983, Adjusted R-squared:  0.9794 
F-statistic:   273 on 24 and 113 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The issue of collinearity is not resolved, but removing influential points is not a typical fix for such an issue. More important is whether the removal of influential points pushed the residuals towards normality and/or constant variance. We thus retest the assumptions of ordinary least squares using <code>diagnostics()</code>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="SLMFinal_files/figure-html/Full OLS (no influential points) diagnostics-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="SLMFinal_files/figure-html/Full OLS (no influential points) diagnostics-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Non-constant Variance Score Test 
Variance formula: ~ fitted.values 
Chisquare = 1.930575, Df = 1, p = 0.1647

    Shapiro-Wilk normality test

data:  resid(lm)
W = 0.9888, p-value = 0.3309</code></pre>
</div>
</div>
<p>We see that the left tail of the Residuals vs.&nbsp;Fitted plot is still largely positive, but that the spread of the rest of the data is more evenly distributed between positive and negative. The non-constant variance test returns a <span class="math inline">\(p\)</span>-value of <span class="math inline">\(p=0.1647&gt;0.05\)</span>, meaning we fail to reject the null hypothesis of homoskedasticity. The Q-Q plot and Shapiro-Wilk’s test maintain the approximate normality of the residuals from the version of the model that included the influential points. Thus, upon removal of the influential points, the Full OLS model was able to fit all necessary assumptions.</p>
</section>
<section id="transformations" class="level2">
<h2 class="anchored" data-anchor-id="transformations">Transformations</h2>
<p>The removal of influential points allows us to investigate the necessity for a transformation of the response with greater precision. Thus, since we identified a nonlinear relationship between the response and some of the predictors (most notably GDP per capita) in the exploratory data analysis, we now run the Box-Cox transformation of the response variable. The Box-Cox transformation procedure calculates the log-likelhood of the different values of <span class="math inline">\(\lambda\)</span> as in the following power transformation: <span class="math display">\[g_\lambda (y)=\begin{cases}y^\lambda &amp; \lambda \not= 0 \\ \log{y} &amp; \lambda = 0\end{cases}\]</span></p>
<p>We use the Full OLS model with no influential points as the basis of this computation, plotting the log-likelihood function of <span class="math inline">\(\lambda\)</span> and identifying its 95% confidence interval.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="SLMFinal_files/figure-html/Box-Cox plot-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>First, we note that <span class="math inline">\(\lambda=1\)</span> is not included in the 95% confidence interval, which tells us that a transformation does need to occur. The 95% confidence interval is not too wide, just over 1 in length, which tells us that there is not a large level of uncertainty in the necessary trasnformation. Finally, the estimated value of <span class="math inline">\(\lambda\)</span> is very close to 0 — which corresponds to a transformation by taking <span class="math inline">\(\log{y}\)</span>. Thus, we fit and summarize the Box-Cox transformed linear model below, in which the response of life expectancy is replaced by the natural logarithm of life expectancy.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Life_expectancy) ~ Region + Infant_deaths + 
    Under_five_deaths + Adult_mortality + Alcohol_consumption + 
    Hepatitis_B + Measles + BMI + Polio + Diphtheria + Incidents_HIV + 
    GDP_per_capita + Population_mln + Thinness_ten_nineteen_years + 
    Thinness_five_nine_years + Schooling + Economy_status_Developing, 
    data = train_lifeexp_clean)

Residuals:
       Min         1Q     Median         3Q        Max 
-0.0307761 -0.0087394 -0.0003242  0.0087046  0.0309040 

Coefficients:
                                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                          4.514e+00  3.449e-02 130.863  &lt; 2e-16 ***
RegionAsia                           1.429e-03  6.140e-03   0.233  0.81634    
RegionCentral America and Caribbean  1.684e-02  6.244e-03   2.696  0.00808 ** 
RegionEuropean Union                -1.713e-02  9.078e-03  -1.887  0.06179 .  
RegionMiddle East                    5.096e-03  7.195e-03   0.708  0.48025    
RegionNorth America                 -6.391e-03  1.361e-02  -0.469  0.63962    
RegionOceania                       -2.284e-02  7.765e-03  -2.941  0.00397 ** 
RegionRest of Europe                -1.710e-03  7.397e-03  -0.231  0.81756    
RegionSouth America                  2.170e-02  6.977e-03   3.110  0.00237 ** 
Infant_deaths                       -8.061e-04  5.905e-04  -1.365  0.17492    
Under_five_deaths                   -1.102e-03  3.822e-04  -2.883  0.00471 ** 
Adult_mortality                     -7.090e-04  3.944e-05 -17.977  &lt; 2e-16 ***
Alcohol_consumption                 -1.422e-04  6.662e-04  -0.213  0.83139    
Hepatitis_B                         -2.868e-04  3.251e-04  -0.882  0.37960    
Measles                              1.515e-04  1.118e-04   1.354  0.17833    
BMI                                 -1.200e-03  1.157e-03  -1.037  0.30194    
Polio                               -2.083e-04  3.162e-04  -0.659  0.51143    
Diphtheria                           3.481e-04  3.748e-04   0.929  0.35501    
Incidents_HIV                        4.698e-03  1.444e-03   3.254  0.00150 ** 
GDP_per_capita                       1.662e-07  1.155e-07   1.439  0.15283    
Population_mln                       1.484e-05  1.345e-05   1.103  0.27229    
Thinness_ten_nineteen_years         -1.310e-02  8.596e-03  -1.524  0.13035    
Thinness_five_nine_years             1.226e-02  8.426e-03   1.455  0.14853    
Schooling                           -1.935e-03  1.089e-03  -1.776  0.07840 .  
Economy_status_Developing           -4.201e-02  8.971e-03  -4.683 7.93e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.01459 on 113 degrees of freedom
Multiple R-squared:  0.9859,    Adjusted R-squared:  0.9829 
F-statistic: 329.7 on 24 and 113 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We see similar strengths and weaknesses between this model and the Full OLS model: high <span class="math inline">\(R^2\)</span> and low standard error indicating that the linear model is an accurate fit for the data, but a high <span class="math inline">\(R^2\)</span> with a low number of significant predictors indicating collinearity. Using the function from the diagnostics section above, we may also see how the Box-Cox transformed model fits the assumptions of ordinary least squares regression.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="SLMFinal_files/figure-html/Box-Cox diagnostics-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="SLMFinal_files/figure-html/Box-Cox diagnostics-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Non-constant Variance Score Test 
Variance formula: ~ fitted.values 
Chisquare = 4.242568, Df = 1, p = 0.039422

    Shapiro-Wilk normality test

data:  resid(lm)
W = 0.99165, p-value = 0.5892</code></pre>
</div>
</div>
<p>In the Residuals vs.&nbsp;Fitted plot above, we see a much wider dispersion of residuals in the lefthand side of the data than in the righthand side. This results in a non-constant variance test <span class="math inline">\(p\)</span>-value of <span class="math inline">\(p=0.039422&lt;0.05\)</span>, meaning we reject the null hypothesis of homoskedasticity. The normality assumption is met by both the Q-Q plot and the Shapiro-Wilks test of normality. Thus, the Box-Cox transformation returns the model to meeting only one of the assumptions (normality) while failing to meet the other (homoskedasticity).</p>
</section>
<section id="collinearity" class="level2">
<h2 class="anchored" data-anchor-id="collinearity">Collinearity</h2>
<p>One of the recurring issues with the various models presented in this report thus far has been a presence of collinearity, which we have identified from the combination of high <span class="math inline">\(R^2\)</span> and low number of significant predictors. In this section, we will use several strategies to more formally assess collinearity in the previous models.</p>
<p>To begin, we wrote a function (<code>cond_nums()</code>) which calculates and displays the eigenvalues and condition numbers of the matrix <span class="math inline">\(X^TX\)</span> (where <span class="math inline">\(X\)</span> is the matrix of observations of predictor variables). The condition numbers <span class="math inline">\(\kappa_i=\sqrt{\frac{\lambda_i}{\lambda_p}}\)</span> (where <span class="math inline">\(\lambda_p\)</span> is the smallest eigenvalue) give an indication of the amount of collinearity between predictor variables. A condition number is considered large if <span class="math inline">\(\kappa_i\geq 30\)</span>.</p>
<p>We first find the condition numbers for the Full OLS model with no influential points below. We have chosen to evaluate this model in particular since it is our best bet so far for a model that fits assumptions and is a good fit for the data.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-6efb309a{}.cl-6eef5cd4{font-family:'Arial';font-size:10pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-6ef610ba{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-6ef645a8{width:1.714in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6ef645b2{width:1.405in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6ef645bc{width:1.714in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6ef645c6{width:1.405in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6ef645c7{width:1.714in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6ef645d0{width:1.405in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6ef645da{width:1.714in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6ef645db{width:1.405in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-6efb309a"><thead><tr style="overflow-wrap:break-word;"><th class="cl-6ef645a8"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">Eigenvalue</span></p></th><th class="cl-6ef645b2"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">Condition.Number</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-6ef645bc"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">74050849056.4214325</span></p></td><td class="cl-6ef645c6"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">1.0000</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6ef645bc"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">6727341.1288215</span></p></td><td class="cl-6ef645c6"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">104.9164</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6ef645bc"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">1823640.9990563</span></p></td><td class="cl-6ef645c6"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">201.5094</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6ef645bc"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">515134.9368935</span></p></td><td class="cl-6ef645c6"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">379.1443</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6ef645bc"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">40793.0663706</span></p></td><td class="cl-6ef645c6"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">1347.3234</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6ef645c7"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">19464.9809425</span></p></td><td class="cl-6ef645d0"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">1950.4644</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6ef645bc"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">3542.2061105</span></p></td><td class="cl-6ef645c6"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">4572.2304</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6ef645bc"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">2677.7580354</span></p></td><td class="cl-6ef645c6"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">5258.7116</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6ef645bc"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">1532.0493324</span></p></td><td class="cl-6ef645c6"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">6952.3023</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6ef645c7"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">1247.1788626</span></p></td><td class="cl-6ef645d0"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">7705.4969</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6ef645bc"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">846.1002935</span></p></td><td class="cl-6ef645c6"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">9355.2220</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6ef645bc"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">513.2585450</span></p></td><td class="cl-6ef645c6"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">12011.4912</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6ef645c7"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">217.6688155</span></p></td><td class="cl-6ef645d0"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">18444.5012</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6ef645bc"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">122.4282351</span></p></td><td class="cl-6ef645c6"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">24593.7201</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6ef645bc"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">18.4416299</span></p></td><td class="cl-6ef645c6"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">63367.3244</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6ef645bc"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">13.0505677</span></p></td><td class="cl-6ef645c6"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">75326.9391</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6ef645bc"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">10.6055142</span></p></td><td class="cl-6ef645c6"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">83560.1393</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6ef645bc"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">9.7137823</span></p></td><td class="cl-6ef645c6"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">87311.3770</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6ef645c7"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">7.2981564</span></p></td><td class="cl-6ef645d0"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">100729.9085</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6ef645bc"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">5.9133325</span></p></td><td class="cl-6ef645c6"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">111904.8405</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6ef645bc"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">2.2267879</span></p></td><td class="cl-6ef645c6"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">182358.3271</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6ef645bc"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">1.8612311</span></p></td><td class="cl-6ef645c6"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">199464.1618</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6ef645c7"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">1.5082902</span></p></td><td class="cl-6ef645d0"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">221575.9252</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6ef645da"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">0.7398552</span></p></td><td class="cl-6ef645db"><p class="cl-6ef610ba"><span class="cl-6eef5cd4">316367.3471</span></p></td></tr></tbody></table></div>
</div>
</div>
<p>Unsurprisingly, all of the condition numbers are greater than 30, indicating a high level of collinearity — in particular, this means that collinearity is being caused by many different approximate linear combinations between predictors.</p>
<p>Another measure of collinearity is the Variance Inflation Factor (VIF). Since collinearity leads to unstable estimations of the coefficients <span class="math inline">\(\beta\)</span>, we can observe the effect of collinearity in the expression of the variance of <span class="math inline">\(\hat\beta\)</span> for a given predictor <span class="math inline">\(x_j\)</span>, <span class="math inline">\(\textrm{var}(\hat\beta_j)=\sigma^2\left(\frac{1}{1-R^2_j}\right)\frac{1}{\sum_i(x_{ij}-\bar x_j)^2}\)</span>. The variance inflation factor is derived from this expression and defined as <span class="math inline">\((1-R_j^2)^{-1}\)</span> and is large if and only if <span class="math inline">\(\textrm{var}(\hat\beta_j)\)</span> is large.</p>
<p>We calculate the VIFs of the predictors in the Full OLS model with no influential points below.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>                                  GVIF Df GVIF^(1/(2*Df))
Region                      100.474932  8        1.333916
Infant_deaths                93.055043  1        9.646504
Under_five_deaths            87.937560  1        9.377503
Adult_mortality               7.899828  1        2.810663
Alcohol_consumption           4.261877  1        2.064431
Hepatitis_B                  15.428785  1        3.927949
Measles                       2.013224  1        1.418881
BMI                           3.614704  1        1.901238
Polio                        11.808635  1        3.436369
Diphtheria                   21.785879  1        4.667535
Incidents_HIV                 2.539843  1        1.593689
GDP_per_capita                2.990740  1        1.729376
Population_mln                1.568307  1        1.252321
Thinness_ten_nineteen_years 820.074088  1       28.636936
Thinness_five_nine_years    806.283567  1       28.395133
Schooling                     7.137980  1        2.671700
Economy_status_Developing     9.292191  1        3.048309</code></pre>
</div>
</div>
<p>A VIF of exactly 1 indicates perfectly orthogonal variables; thus, we hope for VIFs not much larger than 1. Here, we see several much larger than 1, including <code>Infant_deaths</code>, <code>Under_five_deaths</code>, <code>Hepatitis_B</code>, <code>Diphtheria</code>, <code>Thinness_ten_nineteen_years</code>, and <code>Thinness_five_nine_years</code>. Qualitatively, these make sense: counts of childhood mortality are likely collinear to each other, rates of vaccine coverage are likely collinear to each other, and measures of thinness are by definition collinear to BMI (since their calculation is based off extreme BMI values).</p>
<p>With the above two assessments, we have identified a continued presence of collinearity in our models. Thus, in the following section, we will use the model selection technique of stepwise elimination to attempt to reduce collinearity.</p>
</section>
<section id="model-selection" class="level2">
<h2 class="anchored" data-anchor-id="model-selection">Model Selection</h2>
<p>Model selection techniques are used to optimally select a subset of predictors. The technique we will rely on in this section is stepwise elimination, which evaluates the AIC (Akaike’s Information Criterion) of different models using a sequential search method. We include the summary of the model chosen by stepwise elimination below. The starting model is the Full OLS model with no influential points.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Life_expectancy ~ Region + Infant_deaths + Under_five_deaths + 
    Adult_mortality + Measles + Incidents_HIV + GDP_per_capita + 
    Thinness_ten_nineteen_years + Thinness_five_nine_years + 
    Schooling + Economy_status_Developing, data = train_lifeexp_clean)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.20377 -0.81907  0.00906  0.69463  2.73534 

Coefficients:
                                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                          8.572e+01  1.235e+00  69.382  &lt; 2e-16 ***
RegionAsia                           3.123e-01  4.525e-01   0.690 0.491454    
RegionCentral America and Caribbean  1.334e+00  4.338e-01   3.075 0.002608 ** 
RegionEuropean Union                -1.165e+00  6.562e-01  -1.775 0.078453 .  
RegionMiddle East                    4.969e-01  4.871e-01   1.020 0.309706    
RegionNorth America                  2.215e-01  8.913e-01   0.248 0.804199    
RegionOceania                       -1.521e+00  5.279e-01  -2.882 0.004685 ** 
RegionRest of Europe                 3.159e-01  5.210e-01   0.606 0.545512    
RegionSouth America                  1.808e+00  4.957e-01   3.647 0.000394 ***
Infant_deaths                       -8.324e-02  4.286e-02  -1.942 0.054507 .  
Under_five_deaths                   -4.085e-02  2.764e-02  -1.478 0.142140    
Adult_mortality                     -4.906e-02  2.872e-03 -17.081  &lt; 2e-16 ***
Measles                              1.154e-02  7.599e-03   1.519 0.131467    
Incidents_HIV                        3.989e-01  1.070e-01   3.729 0.000295 ***
GDP_per_capita                       2.043e-05  8.613e-06   2.372 0.019309 *  
Thinness_ten_nineteen_years         -8.910e-01  6.292e-01  -1.416 0.159364    
Thinness_five_nine_years             8.518e-01  6.161e-01   1.383 0.169352    
Schooling                           -1.531e-01  7.314e-02  -2.093 0.038473 *  
Economy_status_Developing           -3.774e+00  6.131e-01  -6.154 1.05e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.095 on 119 degrees of freedom
Multiple R-squared:  0.9823,    Adjusted R-squared:  0.9796 
F-statistic: 366.6 on 18 and 119 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>On first glance, we see a greater proportion of significant predictors than in the Full OLS model, with an equivalent <span class="math inline">\(R^2\)</span> and smaller residual standard errors. Thus, this model is an improvement from the OLS model.</p>
<p>We can also observe the effect of stepwise elimination on the collinearity of the model. We generate the condition numbers and VIFs of the predictors in the stepwise elimination model.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-6f221566{}.cl-6f1a3b66{font-family:'Arial';font-size:10pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-6f1ce0d2{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-6f1cfe6e{width:1.714in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6f1cfe82{width:1.405in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6f1cfe83{width:1.714in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6f1cfe8c{width:1.405in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6f1cfe96{width:1.714in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6f1cfea0{width:1.405in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6f1cfeaa{width:1.714in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6f1cfeab{width:1.405in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-6f221566"><thead><tr style="overflow-wrap:break-word;"><th class="cl-6f1cfe6e"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">Eigenvalue</span></p></th><th class="cl-6f1cfe82"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">Condition.Number</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-6f1cfe83"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">74049520575.4937439</span></p></td><td class="cl-6f1cfe8c"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">1.0000</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f1cfe83"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">4872096.5251508</span></p></td><td class="cl-6f1cfe8c"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">123.2830</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f1cfe83"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">177993.3280916</span></p></td><td class="cl-6f1cfe8c"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">644.9993</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f1cfe83"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">40626.3725865</span></p></td><td class="cl-6f1cfe8c"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">1350.0725</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f1cfe83"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">3546.2895803</span></p></td><td class="cl-6f1cfe8c"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">4569.5562</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f1cfe83"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">627.8433933</span></p></td><td class="cl-6f1cfe8c"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">10860.1409</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f1cfe83"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">412.8954820</span></p></td><td class="cl-6f1cfe8c"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">13391.8649</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f1cfe83"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">139.8098264</span></p></td><td class="cl-6f1cfe8c"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">23014.0089</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f1cfe83"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">24.6839036</span></p></td><td class="cl-6f1cfe8c"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">54771.4458</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f1cfe83"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">14.3741216</span></p></td><td class="cl-6f1cfe8c"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">71774.5484</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f1cfe83"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">12.4624308</span></p></td><td class="cl-6f1cfe8c"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">77083.2018</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f1cfe96"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">10.8404974</span></p></td><td class="cl-6f1cfea0"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">82648.7940</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f1cfe83"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">9.3478039</span></p></td><td class="cl-6f1cfe8c"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">89003.3451</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f1cfe83"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">7.8056231</span></p></td><td class="cl-6f1cfe8c"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">97399.6365</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f1cfe96"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">2.9741046</span></p></td><td class="cl-6f1cfea0"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">157791.2828</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f1cfe83"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">2.3905556</span></p></td><td class="cl-6f1cfe8c"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">175999.6075</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f1cfe83"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">1.6836676</span></p></td><td class="cl-6f1cfe8c"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">209716.6679</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f1cfeaa"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">0.9839026</span></p></td><td class="cl-6f1cfeab"><p class="cl-6f1ce0d2"><span class="cl-6f1a3b66">274337.4357</span></p></td></tr></tbody></table></div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                                  GVIF Df GVIF^(1/(2*Df))
Region                       31.081302  8        1.239599
Infant_deaths                87.034271  1        9.329216
Under_five_deaths            81.675042  1        9.037425
Adult_mortality               7.437792  1        2.727231
Measles                       1.649742  1        1.284423
Incidents_HIV                 2.473247  1        1.572656
GDP_per_capita                2.952240  1        1.718209
Thinness_ten_nineteen_years 779.870479  1       27.926161
Thinness_five_nine_years    765.094694  1       27.660345
Schooling                     5.709675  1        2.389493
Economy_status_Developing     7.704286  1        2.775660</code></pre>
</div>
</div>
<p>Collinearity seems not to have improved significantly. The condition numbers are once again all greater than 30, and the VIFs that were exceptionally large continue to be so (<code>Infant_deaths</code>, <code>Under_five_deaths</code>, <code>Thinness_ten_nineteen_years</code>, and <code>Thinness_five_nine_years</code> in particular). Thus, the stepwise elimination did not resolve our problem with collinearity.</p>
<p>However, we can combine stepwise elimination with our previous Box-Cox transformation. We display a summary of this model below.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Life_expectancy) ~ Region + Under_five_deaths + 
    Adult_mortality + Incidents_HIV + GDP_per_capita + Schooling + 
    Economy_status_Developing, data = train_lifeexp_clean)

Residuals:
       Min         1Q     Median         3Q        Max 
-0.0296250 -0.0106049  0.0006479  0.0085137  0.0285783 

Coefficients:
                                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                          4.474e+00  1.331e-02 336.282  &lt; 2e-16 ***
RegionAsia                           1.105e-03  5.204e-03   0.212 0.832130    
RegionCentral America and Caribbean  1.735e-02  5.549e-03   3.126 0.002211 ** 
RegionEuropean Union                -1.534e-02  8.449e-03  -1.816 0.071864 .  
RegionMiddle East                    2.853e-03  6.327e-03   0.451 0.652786    
RegionNorth America                  2.165e-03  1.159e-02   0.187 0.852171    
RegionOceania                       -2.342e-02  6.481e-03  -3.613 0.000439 ***
RegionRest of Europe                 3.368e-03  6.660e-03   0.506 0.613968    
RegionSouth America                  2.194e-02  6.280e-03   3.493 0.000665 ***
Under_five_deaths                   -1.556e-03  1.135e-04 -13.713  &lt; 2e-16 ***
Adult_mortality                     -7.138e-04  3.714e-05 -19.219  &lt; 2e-16 ***
Incidents_HIV                        3.933e-03  1.352e-03   2.909 0.004310 ** 
GDP_per_capita                       1.573e-07  1.134e-07   1.387 0.167841    
Schooling                           -1.624e-03  8.670e-04  -1.873 0.063496 .  
Economy_status_Developing           -4.581e-02  8.048e-03  -5.693 8.67e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.01447 on 123 degrees of freedom
Multiple R-squared:  0.9849,    Adjusted R-squared:  0.9832 
F-statistic: 573.8 on 14 and 123 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Again, we see very small residual standard errors, many significant predictors, and a high <span class="math inline">\(R^2\)</span>. Let us check the collinearity.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-6f4ccedc{}.cl-6f423d82{font-family:'Arial';font-size:10pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-6f451fe8{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-6f453942{width:1.637in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6f45394c{width:1.405in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6f45394d{width:1.637in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6f453956{width:1.405in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6f453960{width:1.637in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6f453961{width:1.405in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6f45396a{width:1.637in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6f453974{width:1.405in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-6f4ccedc"><thead><tr style="overflow-wrap:break-word;"><th class="cl-6f453942"><p class="cl-6f451fe8"><span class="cl-6f423d82">Eigenvalue</span></p></th><th class="cl-6f45394c"><p class="cl-6f451fe8"><span class="cl-6f423d82">Condition.Number</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-6f45394d"><p class="cl-6f451fe8"><span class="cl-6f423d82">74049137028.965195</span></p></td><td class="cl-6f453956"><p class="cl-6f451fe8"><span class="cl-6f423d82">1.0000</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f45394d"><p class="cl-6f451fe8"><span class="cl-6f423d82">4351935.852037</span></p></td><td class="cl-6f453956"><p class="cl-6f451fe8"><span class="cl-6f423d82">130.4424</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f45394d"><p class="cl-6f451fe8"><span class="cl-6f423d82">40903.279235</span></p></td><td class="cl-6f453956"><p class="cl-6f451fe8"><span class="cl-6f423d82">1345.4914</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f45394d"><p class="cl-6f451fe8"><span class="cl-6f423d82">1455.681078</span></p></td><td class="cl-6f453956"><p class="cl-6f451fe8"><span class="cl-6f423d82">7132.2553</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f45394d"><p class="cl-6f451fe8"><span class="cl-6f423d82">151.971149</span></p></td><td class="cl-6f453956"><p class="cl-6f451fe8"><span class="cl-6f423d82">22073.9181</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f453960"><p class="cl-6f451fe8"><span class="cl-6f423d82">28.984278</span></p></td><td class="cl-6f453961"><p class="cl-6f451fe8"><span class="cl-6f423d82">50545.0645</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f45394d"><p class="cl-6f451fe8"><span class="cl-6f423d82">17.392377</span></p></td><td class="cl-6f453956"><p class="cl-6f451fe8"><span class="cl-6f423d82">65250.0017</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f45394d"><p class="cl-6f451fe8"><span class="cl-6f423d82">14.353126</span></p></td><td class="cl-6f453956"><p class="cl-6f451fe8"><span class="cl-6f423d82">71826.8374</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f45394d"><p class="cl-6f451fe8"><span class="cl-6f423d82">11.944447</span></p></td><td class="cl-6f453956"><p class="cl-6f451fe8"><span class="cl-6f423d82">78736.6591</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f45394d"><p class="cl-6f451fe8"><span class="cl-6f423d82">9.704332</span></p></td><td class="cl-6f453956"><p class="cl-6f451fe8"><span class="cl-6f423d82">87352.8701</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f45394d"><p class="cl-6f451fe8"><span class="cl-6f423d82">9.314693</span></p></td><td class="cl-6f453956"><p class="cl-6f451fe8"><span class="cl-6f423d82">89161.1653</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f45394d"><p class="cl-6f451fe8"><span class="cl-6f423d82">3.553624</span></p></td><td class="cl-6f453956"><p class="cl-6f451fe8"><span class="cl-6f423d82">144352.4770</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f45394d"><p class="cl-6f451fe8"><span class="cl-6f423d82">2.459924</span></p></td><td class="cl-6f453956"><p class="cl-6f451fe8"><span class="cl-6f423d82">173499.8731</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f45396a"><p class="cl-6f451fe8"><span class="cl-6f423d82">1.119023</span></p></td><td class="cl-6f453974"><p class="cl-6f451fe8"><span class="cl-6f423d82">257241.2245</span></p></td></tr></tbody></table></div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                               GVIF Df GVIF^(1/(2*Df))
Region                    13.851037  8        1.178535
Under_five_deaths          7.882325  1        2.807548
Adult_mortality            7.119739  1        2.668284
Incidents_HIV              2.263468  1        1.504483
GDP_per_capita             2.929148  1        1.711475
Schooling                  4.593577  1        2.143263
Economy_status_Developing  7.599101  1        2.756647</code></pre>
</div>
</div>
<p>The condition numbers are still very large, but the VIFs have decreased notably. Thus, the combination of the absence of influential points, the Box-Cox transformation, and predictors chosen via stepwise elimination allows a reduction in collinearity. This in turn stabilizes the estimates of the coefficients, <span class="math inline">\(\hat\beta\)</span>, allowing for more accurate interpretability of the model.</p>
<p>Alongside collinearity, we can also check diagnostics of both models above.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="SLMFinal_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="SLMFinal_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Non-constant Variance Score Test 
Variance formula: ~ fitted.values 
Chisquare = 1.32929, Df = 1, p = 0.24893

    Shapiro-Wilk normality test

data:  resid(lm)
W = 0.98694, p-value = 0.2166</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="SLMFinal_files/figure-html/unnamed-chunk-13-3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="SLMFinal_files/figure-html/unnamed-chunk-13-4.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Non-constant Variance Score Test 
Variance formula: ~ fitted.values 
Chisquare = 2.851855, Df = 1, p = 0.091269

    Shapiro-Wilk normality test

data:  resid(lm)
W = 0.98247, p-value = 0.07385</code></pre>
</div>
</div>
<p>We see that both stepwise-elimination-chosen models fit the necessary assumptions, as demonstrated by the plots and <span class="math inline">\(p\)</span>-values greater than 0.05 above. Thus, while not fully eliminating collinearity, the model selection via stepwise elimination did result in the model’s adherence to assumptions.</p>
</section>
<section id="shrinkage-methods" class="level2">
<h2 class="anchored" data-anchor-id="shrinkage-methods">Shrinkage Methods</h2>
<p>To accomplish our secondary goal of model accuracy when faced with new data, we consider different shrinkage methods for linear models.</p>
<p>To begin, we use principal component analysis to construct a regression model. This method is useful for our modelling purposes because of the level of collinearity between predictors. Principal component analysis/regression builds a model based on principal components, which are representations of the variation in the data. Since principal components are orthogonal, collinearity is resolved.</p>
<p>We begin by generating the principal components from the training dataset. The standard deviation of each component is listed below.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code> [1] 18694.096   159.949    82.629    24.598    15.799    11.650     4.836
 [8]     4.230     3.128     3.062     1.973     1.500     1.284     1.254
[15]     1.107     0.470     0.300     0.000</code></pre>
</div>
</div>
<p>We see a steep dropoff in magnitude of the first and second components’ standard deviations (the first component’s standard deviation is 116.8754 times the second’s). The drop between the second and third standard deviations is much less sizeable (the second is less than twice the third). In comparison, the remaining components account for a miniscule amount of all variation present in the training dataset. We can view this as well in the Scree Plot below, which plots the standard deviation of the principal components against their component number.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="SLMFinal_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>From the Scree Plot and the standard deviations themselves, we believe a cutoff of 2 components is sufficient for our model. We thus build a principal component regression (PCR) model, a summary of which is displayed below.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>Data:   X dimension: 138 24 
    Y dimension: 138 1
Fit method: svdpc
Number of components considered: 2
TRAINING: % variance explained
                      1 comps  2 comps
X                       99.99   100.00
log(Life_expectancy)    36.20    36.52</code></pre>
</div>
</div>
<p>As expected, we see that 100% of the variance of all predictors is explained with only two components.</p>
<p>We also consider partial least squares (PLS) regression. While PCR produces linear combinations of predictors that minimize collinearity by tending towards orthogonality, it does not consider the response variable in its construction of linear combinations. Partial least squares does. Thus, we build a model with all predictors, and include the Box-Cox transformation, which has been shown to have improved fit in previous sections.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="SLMFinal_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>The above plot displays the number of components included in the partial least squares regression against their respective cross-validated error (in root mean squared error). We once again see a steep dropoff with the inclusion of only a few components. In particular, the error seems to stabilize and minimize with four components.</p>
<p>Finally, we consider ridge regression. Ridge regression is particularly useful when faced with unstable, collinear coefficients <span class="math inline">\(\hat\beta\)</span>. It works by normalizing the regression coefficients, then minimizing the normalized coefficients. Formally, ridge regression seeks to minimize <span class="math inline">\(\beta\)</span> in the expression <span class="math display">\[(y-X\beta)^T(y-X\beta)+\lambda\sum_j\beta_j^2\]</span> for some <span class="math inline">\(\lambda\geq 0\)</span>. We build the ridge regression model and return the value of <span class="math inline">\(\lambda\)</span> that minimizes this expression for our specific dataset.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code> 1.40703518 
         29 </code></pre>
</div>
</div>
<p>We see that a value of <span class="math inline">\(\lambda\approx 1.4\)</span> minimizes the normalized <span class="math inline">\(\hat\beta\)</span>.</p>
<p>We will compare the efficacy of each model via their root mean squared error in the final section. However, to conclude this section, it is important to mention the limitations of the shrinkage methods described here. In general, they reduce the amount of explanatory power given by a model. Individual coefficients lose their attachment to real-world variables. Thus, while typically powerful prediction techniques, shrinkage methods come at the cost of reduced descriptive capabilities. Additionally, shrinkage methods only work with purely numeric predictors, meaning we have lost the ability to include the categorical variable <code>Region</code> in these models. In the following section, a model will be considered built solely on this categorical variable via one-way ANOVA.</p>
</section>
<section id="anova" class="level2">
<h2 class="anchored" data-anchor-id="anova">ANOVA</h2>
<p>Analysis of Variance (ANOVA) models can be used to quantify relationships between different groups/levels of categorical variables. In particular, they can characterize the proportional size of within-group variation versus between-group variation. They are constructed the same way as linear regression models, with the condition that all predictors must be categorical. In this section, we will begin by visually assessing ANOVA of one or multiple factors, then build the most suitable ANOVA model.</p>
<p>With regards to our dataset, there are two categorical variables of interest: <code>Region</code> (one of 9 geopolitical regions) and <code>Economy_status_developing</code> (binary, 1 = developing country and 0 = developed country). We are interested in whether some level of variation in the response, life expectancy, can be attributed to these variables alone. In other words, we would like to see whether being a citizen of “developed” or “developing” country can predict your life expectancy, and the equivalent for region. We will look both at one-way ANOVA (treating each variable in isolation) and two-way ANOVA (allowing for interactions of the two variables).</p>
<p>To start, let us visualize the between-group variation with box plots. Below we observe the box-and-whisker plot of life expectancy grouped by region.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="SLMFinal_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>While some regions seem to have notable differences in life expectancy (e.g.&nbsp;the jump from Africa to Oceania, or from Oceania to European Union), most immediate jumps between groups seem similar. Nevertheless, there could be some meaningful relationship between the variable’s possible values. Let us now observe life expectancy grouped by country’s economic status.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="SLMFinal_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>We see what could be a meaningful difference between the two groups. However, the large variance of the “developing” group compared to the “developed” group is troubling for modelling purposes.</p>
<p>Now, let us consider visual plots displaying the interaction between region and economic status.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="SLMFinal_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="SLMFinal_files/figure-html/unnamed-chunk-21-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>In both plots, we see an issue that would affect the two-way ANOVA. In the first plot, it is clear that there is not representation of both economy statuses in each region, so a full analysis of the interaction between the variables would be impossible. This pattern carries to the second plot. Thus, we will not build a two-way ANOVA model.</p>
<p>Of the two one-way ANOVA models, the model predicting by region seems more promising. Thus, we provide a summary of that model below.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Life_expectancy ~ Region, data = train_lifeexp_clean)

Residuals:
     Min       1Q   Median       3Q      Max 
-11.9600  -3.0275  -0.0863   2.2350  13.2400 

Coefficients:
                                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                          62.8600     0.8282  75.903  &lt; 2e-16 ***
RegionAsia                            8.7926     1.3962   6.298 4.37e-09 ***
RegionCentral America and Caribbean  10.5525     1.4786   7.137 6.16e-11 ***
RegionEuropean Union                 17.0192     1.2985  13.107  &lt; 2e-16 ***
RegionMiddle East                    11.4500     1.7568   6.518 1.46e-09 ***
RegionNorth America                  15.5400     3.5621   4.363 2.61e-05 ***
RegionOceania                         9.0400     1.8311   4.937 2.41e-06 ***
RegionRest of Europe                 14.1554     1.5913   8.895 4.48e-15 ***
RegionSouth America                  11.3900     1.7568   6.483 1.74e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.899 on 129 degrees of freedom
Multiple R-squared:  0.6157,    Adjusted R-squared:  0.5918 
F-statistic: 25.83 on 8 and 129 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We see a model with only significant predictor values, but with a much lower <span class="math inline">\(R^2\)</span> and much higher residual standard errors than our other models. As a secondary measure of the model’s performance, we test its adherence to assumptions via the <code>diagnostics()</code> function.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="SLMFinal_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="SLMFinal_files/figure-html/unnamed-chunk-23-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Non-constant Variance Score Test 
Variance formula: ~ fitted.values 
Chisquare = 22.82666, Df = 1, p = 1.7729e-06

    Shapiro-Wilk normality test

data:  resid(lm)
W = 0.97403, p-value = 0.009775</code></pre>
</div>
<div class="cell-output-display">
<table class="huxtable" data-quarto-disable-processing="true" style="margin-left: auto; margin-right: auto;">
<colgroup><col><col><col></colgroup><thead>
<tr>
<th class="huxtable-cell huxtable-header" style="text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0.4pt;">Df</th><th class="huxtable-cell huxtable-header" style="text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;">F value</th><th class="huxtable-cell huxtable-header" style="text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0.4pt 0pt;">Pr(&gt;F)</th></tr>
</thead>
<tbody>
<tr>
<td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0.4pt;     background-color: rgb(242, 242, 242);">8</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;     background-color: rgb(242, 242, 242);">1.94</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0pt 0pt;     background-color: rgb(242, 242, 242);">0.059</td></tr>
<tr>
<td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0.4pt;">129</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;">&nbsp;&nbsp;&nbsp;</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0.4pt 0.4pt 0pt;">&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
</tbody>
</table>
</div>
</div>
<p>Even accounting for the discrete levels of the model, the variance does not seem constant: in the residuals vs.&nbsp;fitted plot, the residuals for smallest fitted values are much larger than those for the largest fitted values. Similarly, we see large tails tending away from the desired line on the Q-Q plot. The small <span class="math inline">\(p\)</span>-values on the non-constant variance test and Shapiro-Wilks test of normality could be attributed to the discrete values of the predictor variable. However, we appeal as well to Levene’s test for Homogeneity of Variance, an equivalent to the non-constant variance test built for discrete variables. The small <span class="math inline">\(p\)</span>-value from this test confirms that this model does not fit the assumptions.</p>
<p>Thus, to conclude this section, we note that the ANOVA model is the second-worst of the models built in this report on all essential fronts. In short, region is not a sufficient predictor (on its own) of life expectancy.</p>
</section>
</section>
<section id="results-and-conclusions" class="level1">
<h1>Results and Conclusions</h1>
<p>To conclude our report, we return to the two questions we sought to answer at the outset. First, is GDP per capita a good predictor of life expectancy? Second, what is the best model in terms of predictive ability when faced with new data?</p>
<p>To answer the first question, we first recall that the Full OLS model had greater accuracy than the SLR model, as determined by the nested model hypothesis test. However, <code>GDP_per_capita</code> was chosen as one of the predictors by stepwise elimination both before and after Box-Cox transformation. Thus, GDP per capita may be seen as an important predictor of the average life expectancy in a given country, but not as the important predictor.</p>
<p>To answer the second question, we turn to the following subsection.</p>
<section id="results-evaluating-model-performance" class="level2">
<h2 class="anchored" data-anchor-id="results-evaluating-model-performance">Results: Evaluating Model Performance</h2>
<p>Below is included a table that summarizes the performance of each model built in this paper. We include several measures that paint a picture of the model’s accuracy from several angles. In particular, we include the root mean squared error, defined as <span class="math inline">\(\sqrt{\sum_{i=1}^n (\hat y_i- y_i)^2/n}\)</span>, where <span class="math inline">\(y_i\)</span> is the observed value of the response <span class="math inline">\(y\)</span>, <span class="math inline">\(\hat y_i\)</span> is the corresponding fitted value, and <span class="math inline">\(n\)</span> is the sample size. This is commonly used as a measure of performance for models that do not have associated <span class="math inline">\(R^2\)</span>, adjusted <span class="math inline">\(R^2\)</span>, or residual standard errors, like the shrinkage methods used in this paper.</p>
<p>The columns are as follows: <code>R.Squared</code> corresponds to the multiple <span class="math inline">\(R^2\)</span> value as given in the summary of the linear model; <code>Adj.R.Squared</code> corresponds to the adjusted <span class="math inline">\(R^2\)</span> of the model; RSE corresponds to the residual standard error of the model; <code>RMSE.train</code> corresponds to the root mean squared error between the fitted values and the observed values in the training dataset; <code>RMSE.test</code> corresponds to the root mean squared error between the fitted values and the observed values in the testing dataset; and <code>RMSE.ratio</code> is a measure of the difference between the two other RMSE values, calculated by dividing <code>RMSE.test</code> by <code>RMSE.train</code>. The shrinkage methods do not have associated values for some of these performance metrics, and thus no associated value is listed for those models.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-712e0f22{}.cl-7125c146{font-family:'Arial';font-size:9pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7125c15a{font-family:'Arial';font-size:9pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7129347a{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-71293498{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-712951d0{width:1.463in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-712951da{width:0.81in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-712951db{width:1.046in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-712951ee{width:0.498in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-712951f8{width:0.852in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71295202{width:0.803in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71295203{width:1.463in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7129520c{width:0.81in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71295216{width:1.046in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71295217{width:0.498in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71295218{width:0.852in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71295220{width:0.803in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7129522a{width:1.463in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71295234{width:0.81in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7129523e{width:1.046in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71295248{width:0.498in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71295249{width:0.852in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71295252{width:0.803in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71295253{width:1.463in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7129525c{width:0.81in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71295266{width:1.046in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71295270{width:0.498in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7129527a{width:0.852in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71295284{width:0.803in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71295285{width:1.463in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7129528e{width:0.81in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71295298{width:1.046in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71295299{width:0.498in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-712952a2{width:0.852in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-712952ac{width:0.803in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-712952ad{width:1.463in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-712952b6{width:0.81in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-712952c0{width:1.046in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-712952ca{width:0.498in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-712952cb{width:0.852in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-712952cc{width:0.803in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-712952d4{width:1.463in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-712952d5{width:0.81in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-712952de{width:1.046in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-712952e8{width:0.498in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-712952e9{width:0.852in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-712952f2{width:0.803in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-712952fc{width:1.463in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71295306{width:0.81in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71295307{width:1.046in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71295310{width:0.498in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71295311{width:0.852in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7129531a{width:0.803in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-712e0f22"><thead><tr style="overflow-wrap:break-word;"><th class="cl-712951d0"><p class="cl-7129347a"><span class="cl-7125c146">Model</span></p></th><th class="cl-712951da"><p class="cl-71293498"><span class="cl-7125c146">R.Squared</span></p></th><th class="cl-712951db"><p class="cl-71293498"><span class="cl-7125c146">Adj.R.Squared</span></p></th><th class="cl-712951ee"><p class="cl-71293498"><span class="cl-7125c146">RSE</span></p></th><th class="cl-712951f8"><p class="cl-71293498"><span class="cl-7125c146">RMSE.train</span></p></th><th class="cl-71295202"><p class="cl-71293498"><span class="cl-7125c146">RMSE.test</span></p></th><th class="cl-712951f8"><p class="cl-71293498"><span class="cl-7125c146">RMSE.ratio</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-71295203"><p class="cl-7129347a"><span class="cl-7125c15a">Full OLS</span></p></td><td class="cl-7129520c"><p class="cl-71293498"><span class="cl-7125c15a">0.980</span></p></td><td class="cl-71295216"><p class="cl-71293498"><span class="cl-7125c15a">0.976</span></p></td><td class="cl-71295217"><p class="cl-71293498"><span class="cl-7125c15a">1.225</span></p></td><td class="cl-71295218"><p class="cl-71293498"><span class="cl-7125c15a">1.113</span></p></td><td class="cl-71295220"><p class="cl-71293498"><span class="cl-7125c15a">1.505</span></p></td><td class="cl-71295218"><p class="cl-71293498"><span class="cl-7125c15a">1.352</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7129522a"><p class="cl-7129347a"><span class="cl-7125c15a">SLR (GDP/cap only)</span></p></td><td class="cl-71295234"><p class="cl-71293498"><span class="cl-7125c15a">0.396</span></p></td><td class="cl-7129523e"><p class="cl-71293498"><span class="cl-7125c15a">0.392</span></p></td><td class="cl-71295248"><p class="cl-71293498"><span class="cl-7125c15a">6.133</span></p></td><td class="cl-71295249"><p class="cl-71293498"><span class="cl-7125c15a">6.090</span></p></td><td class="cl-71295252"><p class="cl-71293498"><span class="cl-7125c15a">6.018</span></p></td><td class="cl-71295249"><p class="cl-71293498"><span class="cl-7125c15a">0.988</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-71295253"><p class="cl-7129347a"><span class="cl-7125c15a">Full OLS (no influ. pts.)</span></p></td><td class="cl-7129525c"><p class="cl-71293498"><span class="cl-7125c15a">0.983</span></p></td><td class="cl-71295266"><p class="cl-71293498"><span class="cl-7125c15a">0.979</span></p></td><td class="cl-71295270"><p class="cl-71293498"><span class="cl-7125c15a">1.099</span></p></td><td class="cl-7129527a"><p class="cl-71293498"><span class="cl-7125c15a">11.056</span></p></td><td class="cl-71295284"><p class="cl-71293498"><span class="cl-7125c15a">1.990</span></p></td><td class="cl-7129527a"><p class="cl-71293498"><span class="cl-7125c15a">0.180</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-71295285"><p class="cl-7129347a"><span class="cl-7125c15a">Box-Cox Trans.</span></p></td><td class="cl-7129528e"><p class="cl-71293498"><span class="cl-7125c15a">0.986</span></p></td><td class="cl-71295298"><p class="cl-71293498"><span class="cl-7125c15a">0.983</span></p></td><td class="cl-71295299"><p class="cl-71293498"><span class="cl-7125c15a">0.015</span></p></td><td class="cl-712952a2"><p class="cl-71293498"><span class="cl-7125c15a">68.108</span></p></td><td class="cl-712952ac"><p class="cl-71293498"><span class="cl-7125c15a">65.722</span></p></td><td class="cl-712952a2"><p class="cl-71293498"><span class="cl-7125c15a">0.965</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-712952ad"><p class="cl-7129347a"><span class="cl-7125c15a">Stepwise Elim.</span></p></td><td class="cl-712952b6"><p class="cl-71293498"><span class="cl-7125c15a">0.982</span></p></td><td class="cl-712952c0"><p class="cl-71293498"><span class="cl-7125c15a">0.980</span></p></td><td class="cl-712952ca"><p class="cl-71293498"><span class="cl-7125c15a">1.095</span></p></td><td class="cl-712952cb"><p class="cl-71293498"><span class="cl-7125c15a">11.060</span></p></td><td class="cl-712952cc"><p class="cl-71293498"><span class="cl-7125c15a">1.939</span></p></td><td class="cl-712952cb"><p class="cl-71293498"><span class="cl-7125c15a">0.175</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-712952ad"><p class="cl-7129347a"><span class="cl-7125c15a">Step Elim. &amp; Box-Cox</span></p></td><td class="cl-712952b6"><p class="cl-71293498"><span class="cl-7125c15a">0.985</span></p></td><td class="cl-712952c0"><p class="cl-71293498"><span class="cl-7125c15a">0.983</span></p></td><td class="cl-712952ca"><p class="cl-71293498"><span class="cl-7125c15a">0.014</span></p></td><td class="cl-712952cb"><p class="cl-71293498"><span class="cl-7125c15a">68.108</span></p></td><td class="cl-712952cc"><p class="cl-71293498"><span class="cl-7125c15a">65.724</span></p></td><td class="cl-712952cb"><p class="cl-71293498"><span class="cl-7125c15a">0.965</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-71295285"><p class="cl-7129347a"><span class="cl-7125c15a">PCR</span></p></td><td class="cl-7129528e"><p class="cl-71293498"><span class="cl-7125c15a"></span></p></td><td class="cl-71295298"><p class="cl-71293498"><span class="cl-7125c15a"></span></p></td><td class="cl-71295299"><p class="cl-71293498"><span class="cl-7125c15a"></span></p></td><td class="cl-712952a2"><p class="cl-71293498"><span class="cl-7125c15a">68.103</span></p></td><td class="cl-712952ac"><p class="cl-71293498"><span class="cl-7125c15a">65.721</span></p></td><td class="cl-712952a2"><p class="cl-71293498"><span class="cl-7125c15a">0.965</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-71295285"><p class="cl-7129347a"><span class="cl-7125c15a">PLS</span></p></td><td class="cl-7129528e"><p class="cl-71293498"><span class="cl-7125c15a"></span></p></td><td class="cl-71295298"><p class="cl-71293498"><span class="cl-7125c15a"></span></p></td><td class="cl-71295299"><p class="cl-71293498"><span class="cl-7125c15a"></span></p></td><td class="cl-712952a2"><p class="cl-71293498"><span class="cl-7125c15a">68.098</span></p></td><td class="cl-712952ac"><p class="cl-71293498"><span class="cl-7125c15a">65.724</span></p></td><td class="cl-712952a2"><p class="cl-71293498"><span class="cl-7125c15a">0.965</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-712952d4"><p class="cl-7129347a"><span class="cl-7125c15a">Ridge Regression</span></p></td><td class="cl-712952d5"><p class="cl-71293498"><span class="cl-7125c15a"></span></p></td><td class="cl-712952de"><p class="cl-71293498"><span class="cl-7125c15a"></span></p></td><td class="cl-712952e8"><p class="cl-71293498"><span class="cl-7125c15a"></span></p></td><td class="cl-712952e9"><p class="cl-71293498"><span class="cl-7125c15a">1.285</span></p></td><td class="cl-712952f2"><p class="cl-71293498"><span class="cl-7125c15a">1.652</span></p></td><td class="cl-712952e9"><p class="cl-71293498"><span class="cl-7125c15a">1.286</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-712952fc"><p class="cl-7129347a"><span class="cl-7125c15a">ANOVA</span></p></td><td class="cl-71295306"><p class="cl-71293498"><span class="cl-7125c15a">0.616</span></p></td><td class="cl-71295307"><p class="cl-71293498"><span class="cl-7125c15a">0.592</span></p></td><td class="cl-71295310"><p class="cl-71293498"><span class="cl-7125c15a">4.899</span></p></td><td class="cl-71295311"><p class="cl-71293498"><span class="cl-7125c15a">10.638</span></p></td><td class="cl-7129531a"><p class="cl-71293498"><span class="cl-7125c15a">4.567</span></p></td><td class="cl-71295311"><p class="cl-71293498"><span class="cl-7125c15a">0.429</span></p></td></tr></tbody></table></div>
</div>
</div>
<p>There are roughly three groups of models analyzed: standard models and their variations, shrinkage models, and the ANOVA model. As explained in the ANOVA section, the ANOVA model is the second-worst of all models, so in terms of picking the best model, we will only consider candidates from the first two groups. For the shrinkage method models, a best model is easy to select: the ridge regression has the smallest RMSE for both training and testing datasets.</p>
<p>However, a best model is more difficult to select from the standard models and their variations. The models with Box-Cox transformation applied maximize <span class="math inline">\(R^2\)</span> and adjusted <span class="math inline">\(R^2\)</span>, while minimizing residual standard error. However, their RMSE are the largest of all models on both training and testing sets. The stepwise elimination model without the Box-Cox transformation also emerges as a possible best model due to its low residual standard error, high <span class="math inline">\(R^2\)</span> and adjusted <span class="math inline">\(R^2\)</span>, and low RMSE, especially when faced with new (test) data.</p>
<p>To help select a best of the standard models, we consider whether or not each model meets the assumptions of linear regression. The adherence of each model to the assumptions of homoskedasticity and normality of residuals is summarized in the table below.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-714dba98{}.cl-714386ae{font-family:'Arial';font-size:10pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-714386c2{font-family:'Arial';font-size:10pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7146d96c{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-7146d980{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-7146fe6a{width:2.146in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7146fe74{width:1.374in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7146fe7e{width:0.872in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7146fe88{width:2.146in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7146fe92{width:1.374in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7146fe9c{width:0.872in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7146fe9d{width:2.146in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7146fea6{width:1.374in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7146fea7{width:0.872in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7146feb0{width:2.146in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7146feb1{width:1.374in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7146feba{width:0.872in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7146fec4{width:2.146in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7146fece{width:1.374in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7146fed8{width:0.872in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7146fee2{width:2.146in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7146fee3{width:1.374in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7146feec{width:0.872in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7146feed{width:2.146in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7146fef6{width:1.374in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7146fef7{width:0.872in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-714dba98"><thead><tr style="overflow-wrap:break-word;"><th class="cl-7146fe6a"><p class="cl-7146d96c"><span class="cl-714386ae">Model</span></p></th><th class="cl-7146fe74"><p class="cl-7146d980"><span class="cl-714386ae">Homoskedasticity</span></p></th><th class="cl-7146fe7e"><p class="cl-7146d980"><span class="cl-714386ae">Normality</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-7146fe88"><p class="cl-7146d96c"><span class="cl-714386c2">Full OLS</span></p></td><td class="cl-7146fe92"><p class="cl-7146d980"><span class="cl-714386c2">false</span></p></td><td class="cl-7146fe9c"><p class="cl-7146d980"><span class="cl-714386c2">true</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7146fe9d"><p class="cl-7146d96c"><span class="cl-714386c2">SLR (GDP/cap only)</span></p></td><td class="cl-7146fea6"><p class="cl-7146d980"><span class="cl-714386c2">true</span></p></td><td class="cl-7146fea7"><p class="cl-7146d980"><span class="cl-714386c2">false</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7146feb0"><p class="cl-7146d96c"><span class="cl-714386c2">Full OLS (no influential points)</span></p></td><td class="cl-7146feb1"><p class="cl-7146d980"><span class="cl-714386c2">true</span></p></td><td class="cl-7146feba"><p class="cl-7146d980"><span class="cl-714386c2">true</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7146fec4"><p class="cl-7146d96c"><span class="cl-714386c2">Box-Cox Transformation</span></p></td><td class="cl-7146fece"><p class="cl-7146d980"><span class="cl-714386c2">false</span></p></td><td class="cl-7146fed8"><p class="cl-7146d980"><span class="cl-714386c2">true</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7146fee2"><p class="cl-7146d96c"><span class="cl-714386c2">Stepwise Elimination</span></p></td><td class="cl-7146fee3"><p class="cl-7146d980"><span class="cl-714386c2">true</span></p></td><td class="cl-7146feec"><p class="cl-7146d980"><span class="cl-714386c2">true</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7146fee2"><p class="cl-7146d96c"><span class="cl-714386c2">Box-Cox &amp; Step. Elim.</span></p></td><td class="cl-7146fee3"><p class="cl-7146d980"><span class="cl-714386c2">true</span></p></td><td class="cl-7146feec"><p class="cl-7146d980"><span class="cl-714386c2">true</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7146feed"><p class="cl-7146d96c"><span class="cl-714386c2">One-Way ANOVA</span></p></td><td class="cl-7146fef6"><p class="cl-7146d980"><span class="cl-714386c2">false</span></p></td><td class="cl-7146fef7"><p class="cl-7146d980"><span class="cl-714386c2">false</span></p></td></tr></tbody></table></div>
</div>
</div>
<p>Only three models meet both assumptions: the Full OLS model with no influential points and both stepwise elimination models. Since the stepwise elimination model without the Box-Cox transformation meets both assumptions and does very good on its performance measures, we choose that model as the best of the non-shrinkage models.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>To conclude, we summarize our questions and the answers we were able to discern. Our first question was whether or not GDP per capita has a linear relationship with life expectancy. While there certainly was some form of relationship between the two that could be expressed as linear, life expectancy was better predicted by GDP per capita in conjunction with other predictors. Our second question was which model is best for predicting the response, life expectancy. Our two contenders are the ridge regression model and the stepwise elimination model (with transformation of the response selected via Box-Cox). Which model should be considered best mostly rests on the use of the model. If the goal is solely to predict life expectancy, ridge regression is likely best, due to its minimization properties. However, ridge regression loses explanatory power by the normalization of coefficients inherent to the method. Thus, if prediction of life expectancy in conjunction with coefficients that bear some explanatory power over future observational data, the stepwise elimination model is best. With this, we have answered both questions we sought to resolve at the outset of our project.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
 © Copyright 2026, Emrys King. All rights reserved.
  </li>  
</ul>
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/egkegk/egkegk.github.io">
      <i class="bi bi-github" role="img" aria-label="Quarto GitHub">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>