<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Emrys King">
<meta name="dcterms.date" content="2024-11-26">

<title>Prediction of Global Temperatures with Climate Proxy Variables – Emrys King</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../logo.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-18112a742f95efe2b66f86c4b0e86dd6.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="../site_libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">
<script src="../site_libs/tabwid-1.1.3/tabwid.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../logo.png" alt="A hypercube logo." class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Emrys King</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text"> </span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../cv.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#part-1" id="toc-part-1" class="nav-link" data-scroll-target="#part-1">Part 1</a>
  <ul class="collapse">
  <li><a href="#data-description-and-exploratory-analysis" id="toc-data-description-and-exploratory-analysis" class="nav-link" data-scroll-target="#data-description-and-exploratory-analysis">1. Data Description and Exploratory Analysis</a></li>
  <li><a href="#autoregression" id="toc-autoregression" class="nav-link" data-scroll-target="#autoregression">2. Autoregression</a></li>
  </ul></li>
  <li><a href="#part-2" id="toc-part-2" class="nav-link" data-scroll-target="#part-2">Part 2</a>
  <ul class="collapse">
  <li><a href="#full-model-and-stepwise-elimination" id="toc-full-model-and-stepwise-elimination" class="nav-link" data-scroll-target="#full-model-and-stepwise-elimination">3. Full Model and Stepwise Elimination</a></li>
  <li><a href="#box-cox-transformation" id="toc-box-cox-transformation" class="nav-link" data-scroll-target="#box-cox-transformation">4. Box-Cox Transformation</a></li>
  <li><a href="#parameter-estimates-and-standard-errors" id="toc-parameter-estimates-and-standard-errors" class="nav-link" data-scroll-target="#parameter-estimates-and-standard-errors">5./6. Parameter Estimates and Standard Errors</a></li>
  </ul></li>
  <li><a href="#part-3" id="toc-part-3" class="nav-link" data-scroll-target="#part-3">Part 3</a>
  <ul class="collapse">
  <li><a href="#regression-diagnostics" id="toc-regression-diagnostics" class="nav-link" data-scroll-target="#regression-diagnostics">7. Regression Diagnostics</a></li>
  <li><a href="#unusual-observations" id="toc-unusual-observations" class="nav-link" data-scroll-target="#unusual-observations">8. Unusual Observations</a></li>
  <li><a href="#collinearity" id="toc-collinearity" class="nav-link" data-scroll-target="#collinearity">9. Collinearity</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Prediction of Global Temperatures with Climate Proxy Variables</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Emrys King </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 26, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>In this report, I will be analyzing the dataset <code>globwarm</code>, which reports the Average Northern Hemisphere Temperature from 1856-2000 and eight climate proxies from 1000-2000AD. Using the information from the climate proxies above I will attempt to predict the global temperature in years predating 1856, before which temperatures are unreliable due to the lack of standardization of thermometers. To most accurately predict some of these years, I will build seven different linear regression models and evaluate each in a holistic, comprehensive manner.</p>
<p>Thus, the question I am hoping to answer is: which linear model is best? To answer this question, I will first conduct an exploratory analysis of the dataset and establish the periodicity of the data when viewed from a time series perspective. I will then fit a linear model using ordinary least squares to estimate the parameters <span class="math inline">\(\beta\)</span>, evaluate the need for a transformation of the response variable using Box-Cox, and communicate the parameter estimates and standard errors of the model and their meaning. Finally, I will test the assumptions of ordinary least squares against each model, find influential points in the dataset that may be affecting the fit, and establish the effect of collinearity on the model. In the conclusion, I will communicate overall findings, consider possible best models and the drawbacks to each, and ultimately predict the northern hemisphere temperature in two of the unknown years, 1850 and 1000.</p>
</section>
<section id="part-1" class="level1">
<h1>Part 1</h1>
<section id="data-description-and-exploratory-analysis" class="level2">
<h2 class="anchored" data-anchor-id="data-description-and-exploratory-analysis">1. Data Description and Exploratory Analysis</h2>
<p>To begin, I include here a description of the variables in the dataset <code>globwarm</code>.</p>
<div class="cell">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-8437ef70{}.cl-84358316{font-family:'Arial';font-size:10pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-84358320{font-family:'Arial';font-size:10pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-84369864{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-8436a232{width:1.034in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8436a233{width:5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8436a234{width:1.034in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8436a235{width:5in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8436a23c{width:1.034in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8436a23d{width:5in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8436a23e{width:1.034in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8436a246{width:5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-8437ef70"><thead><tr style="overflow-wrap:break-word;"><th class="cl-8436a232"><p class="cl-84369864"><span class="cl-84358316">Variable</span></p></th><th class="cl-8436a233"><p class="cl-84369864"><span class="cl-84358316">Description</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-8436a234"><p class="cl-84369864"><span class="cl-84358320">nhtemp</span></p></td><td class="cl-8436a235"><p class="cl-84369864"><span class="cl-84358320">Northern hemisphere average temperature (C) provided by the UK Met Office (known as HadCRUT2)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-8436a23c"><p class="cl-84369864"><span class="cl-84358320">wusa</span></p></td><td class="cl-8436a23d"><p class="cl-84369864"><span class="cl-84358320">Tree ring proxy information from the Western USA.</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-8436a23c"><p class="cl-84369864"><span class="cl-84358320">jasper</span></p></td><td class="cl-8436a23d"><p class="cl-84369864"><span class="cl-84358320">Tree ring proxy information from Canada.</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-8436a23c"><p class="cl-84369864"><span class="cl-84358320">westgreen</span></p></td><td class="cl-8436a23d"><p class="cl-84369864"><span class="cl-84358320">Ice core proxy information from west Greenland</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-8436a23c"><p class="cl-84369864"><span class="cl-84358320">chesapeake</span></p></td><td class="cl-8436a23d"><p class="cl-84369864"><span class="cl-84358320">Sea shell proxy information from Chesapeake Bay</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-8436a23c"><p class="cl-84369864"><span class="cl-84358320">tornetrask</span></p></td><td class="cl-8436a23d"><p class="cl-84369864"><span class="cl-84358320">Tree ring proxy information from Sweden</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-8436a23c"><p class="cl-84369864"><span class="cl-84358320">urals</span></p></td><td class="cl-8436a23d"><p class="cl-84369864"><span class="cl-84358320">Tree ring proxy information from the Urals</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-8436a23c"><p class="cl-84369864"><span class="cl-84358320">mongolia</span></p></td><td class="cl-8436a23d"><p class="cl-84369864"><span class="cl-84358320">Tree ring proxy information from Mongolia</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-8436a23c"><p class="cl-84369864"><span class="cl-84358320">tasman</span></p></td><td class="cl-8436a23d"><p class="cl-84369864"><span class="cl-84358320">Tree ring proxy information from Tasmania</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-8436a23e"><p class="cl-84369864"><span class="cl-84358320">year</span></p></td><td class="cl-8436a246"><p class="cl-84369864"><span class="cl-84358320">Year 1000-2000AD</span></p></td></tr></tbody></table></div>
</div>
</div>
<p>Since the goal of this analysis is to predict temperature using the other eight climate variables, it is first necessary to obtain a subset of the data from 1856 onwards, since only these years include data on temperature.</p>
<p>All model building will be based on the dataset <code>globwarm1856</code>, since this dataset is (i.e., not <code>NA</code>) for all values of <code>nhtemp</code>, no matter the <code>year</code>.</p>
<p>To begin, let us visually observe the relationship between year and average global temperature. Included is the standard linear model of best fit in blue, and the kernel-smoothed <code>loess</code> curve of best fit in red.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SLMMidtermExam_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The above graph shows that, though the data certainly has a curve to it, a linear model could be used to fit the relationship between <code>nhtemp</code> and <code>year</code>. In particular, though the residuals do not have constant variance (observe the right tail of the datapoints compared to the other datapoints), a transformation of the response, <code>nhtemp</code>, may result in the meeting of this assumption. Furthermore, in the most general terms, this graph shows that the average temperature in the Northern Hemisphere has been increasing as the years go on.</p>
<p>To further explore the dataset, observe the following graphs of tree growth dependent on year and average temperature. “Tree growth” is agglomerated from all tree ring proxy variables — the source of each datapoint (i.e., the variable it is associated with) is depicted via its color.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SLMMidtermExam_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The above graph, “Tree Growth by Year,” most importantly displays the periodicity of tree growth over time. This pattern indicates that autoregression modelling methods will likely be most appropriate for any model that includes <code>year</code> as a predictor and any tree growth proxy as the response.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SLMMidtermExam_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The above graph shows the truth of the hypothesis guiding this analysis, that information on the rate of tree growth indicates that tree growth increases in warmer temperatures. The slope of the line of best fit is positive, which means that as temperature increases, so does the rate of tree growth.</p>
<p>To conclude the exploratory data analysis, observe the following summary of <code>year</code> in relation to every other variable in the dataset.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SLMMidtermExam_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<p>As noted with the “Tree Growth by Year” plot above, the most important trend to be gleaned is the periodicity of each variable in relation to year. This periodicity is something that cannot accurately be modelled other than by autoregression. For the majority of the analysis, <code>year</code> will be removed from the predictors to be able to use standard linear regression techniques. However, in the following subsection, the autoregressive model predicting <code>wusa</code>, the tree ring proxy information from the western United States, using lagged variables.</p>
</section>
<section id="autoregression" class="level2">
<h2 class="anchored" data-anchor-id="autoregression">2. Autoregression</h2>
<p>To begin, let us focus on the plot of <code>wusa</code> vs.&nbsp;<code>year</code>, with the standard linear model <span class="math inline">\(\texttt{wusa}_i=\hat\beta_0+\hat\beta_1\texttt{year}_i\)</span> overlaid.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SLMMidtermExam_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The periodicity of the plot above violates the assumptions of linear regression: instead of independently and identically distributed residuals centered around a constant, the residuals will follow the periodic nature of the data itself. To account for the time series nature of the given data, one may instead build an autoregressive model by embedding “lagged” data as predictors of a dataframe. The nature of lagged data may be seen below — note how the value of <code>wusa_og</code> in a given observation becomes the value of <code>lag1</code> in the subsequent observation, and how the value of <code>lag1</code> in a given observation becomes the value of <code>lag2</code> in the subsequent observation, and so on.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  wusa_og  lag1  lag2  lag3
1   -0.85 -0.84 -0.81 -0.78
2   -0.84 -0.85 -0.84 -0.81
3   -0.79 -0.84 -0.85 -0.84
4   -0.72 -0.79 -0.84 -0.85
5   -0.62 -0.72 -0.79 -0.84
6   -0.52 -0.62 -0.72 -0.79</code></pre>
</div>
</div>
<p>Using the <code>lagdf</code> dataset, we may predict the value of <code>wusa</code> given its previous values, a technique known as autoregression.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wusa_og ~ ., data = data.frame(lagdf))

Residuals:
       Min         1Q     Median         3Q        Max 
-0.0311282 -0.0074819 -0.0000792  0.0078532  0.0298416 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.003150   0.001333   2.363   0.0195 *  
lag1         2.624708   0.061706  42.536   &lt;2e-16 ***
lag2        -2.311777   0.121175 -19.078   &lt;2e-16 ***
lag3         0.683676   0.060810  11.243   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.01139 on 138 degrees of freedom
Multiple R-squared:  0.9998,    Adjusted R-squared:  0.9998 
F-statistic: 2.085e+05 on 3 and 138 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>From the above summary, one sees that the fit of the autoregressive model predicting <code>wusa</code> is nearly perfect: the <span class="math inline">\(R^2\)</span> value is 0.9998, with the maximum possible <span class="math inline">\(R^2\)</span> being 1. The fit of the model can be seen visually in the plot below. The original <code>wusa</code> data is included as a black solid line, while the autoregressive fit is included as a red dashed line.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SLMMidtermExam_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>It is thus clear that the periodic nature of the <code>wusa</code> data over time is captured by the autoregressive model. The problem with the assumptions that appeared in the standard linear model does not occur here; the periodicity of the data will not be replicated in the residuals.</p>
<p>Now, to employ the autoregression as a predictive model, one must first observe the final entry of <code>lagdf</code> dataset, which corresponds to the data for the year 2000.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    wusa_og lag1 lag2 lag3
142    0.88 0.84 0.82 0.82</code></pre>
</div>
</div>
<p>Due to the nature of the construction of the lagged data, the values of <code>wusa_og</code>, <code>lag1</code>, and <code>lag2</code> may be plugged in for <code>lag1</code>, <code>lag2</code>, and <code>lag3</code>, respectively to predict the value of <code>wusa</code> in 2001. These calculations are accomplished below, and the 95% confidence interval is included in the results.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>        fit       lwr       upr
1 0.9316155 0.9088515 0.9543796</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6089223</code></pre>
</div>
</div>
<p>Thus, the expected value of <code>wusa</code> in 2001 is 0.9316155, with the 95% confidence interval being <span class="math inline">\((0.9088515, 0.9543796)\)</span>. This confidence interval is a bit wide given the spread of the data: in <code>globwarm1856</code>, the variance of <code>wusa</code> is approximately 0.6, which means that a confidence interval of width just under 0.5 is almost equal to the variance of the data.</p>
<p>Similar to the method above, to predict the value of <code>wusa</code> in 2002, one may plug in the values of <code>wusa_og</code>, and <code>lag1</code> from the last row of <code>lagdf</code> for <code>lag2</code> and <code>lag3</code>, while the expected value for 2001 calculated above may be used as the estimate for <code>lag1</code>. The calculation and confidence interval are thus returned.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>        fit       lwr      upr
1 0.9958969 0.9731721 1.018622</code></pre>
</div>
</div>
<p>The expected value of <code>wusa</code> in 2002 is 0.9958969, with the 95% confidence interval being <span class="math inline">\((0.9731721, 1.018622)\)</span>. The width of this confidence interval is approximately 0.3, with is smaller than the width of the previous confidence interval and approximately half of the variance of <code>wusa</code> in <code>globwarm1956</code>.</p>
<p>Autoregression techniques are useful for predicting explicitly time-series data, like tree ring proxy information predicted by year. However, using the climate proxy information in isolation from <code>year</code>, one may build a standard linear regression model without using autoregression. Models of this form will be built and evaluated in the following sections.</p>
</section>
</section>
<section id="part-2" class="level1">
<h1>Part 2</h1>
<section id="full-model-and-stepwise-elimination" class="level2">
<h2 class="anchored" data-anchor-id="full-model-and-stepwise-elimination">3. Full Model and Stepwise Elimination</h2>
<p>To begin, observe the following standard linear regression model, which assigns <code>nhtemp</code> as the response and all eight climate proxies as predictors. This model will be referred to as the “full model,” the linear regression model with no transformations and all possible predictors (except <code>year</code>).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = nhtemp ~ wusa + jasper + westgreen + chesapeake + 
    tornetrask + urals + mongolia + tasman, data = globwarm1856)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.43668 -0.11170  0.00698  0.10176  0.65352 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.242555   0.027011  -8.980 1.97e-15 ***
wusa         0.077384   0.042927   1.803 0.073647 .  
jasper      -0.228795   0.078107  -2.929 0.003986 ** 
westgreen    0.009584   0.041840   0.229 0.819168    
chesapeake  -0.032112   0.034052  -0.943 0.347346    
tornetrask   0.092668   0.045053   2.057 0.041611 *  
urals        0.185369   0.091428   2.027 0.044567 *  
mongolia     0.041973   0.045794   0.917 0.360996    
tasman       0.115453   0.030111   3.834 0.000192 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1758 on 136 degrees of freedom
Multiple R-squared:  0.4764,    Adjusted R-squared:  0.4456 
F-statistic: 15.47 on 8 and 136 DF,  p-value: 5.028e-16</code></pre>
</div>
</div>
<p>From the summary above, one observes half of the variables as significant (<code>jasper</code>, <code>tornetrask</code>, <code>urals</code>, and <code>tasman</code>), with a poor <span class="math inline">\(R^2\)</span> value of 0.4764. The fit of this model may be improved using stepwise regression, which sequentially compares models via their Aikake’s Important Criterion (AIC), defined elimination <span class="math inline">\(AIC=-2L(\hat\theta)+2p\)</span>, where <span class="math inline">\(-2L(\hat\theta)=n\log{(RSS/n)}+c\)</span> for sample size <span class="math inline">\(n\)</span>, number of parameters <span class="math inline">\(p\)</span>, residual sum of squares <span class="math inline">\(RSS\)</span>, and some constant <span class="math inline">\(c\)</span>. This process ceases upon finding the best selection of predictors without a transformation of the response.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=-495.48
nhtemp ~ wusa + jasper + westgreen + chesapeake + tornetrask + 
    urals + mongolia + tasman

             Df Sum of Sq    RSS     AIC
- westgreen   1   0.00162 4.2033 -497.43
- mongolia    1   0.02595 4.2276 -496.59
- chesapeake  1   0.02747 4.2291 -496.54
&lt;none&gt;                    4.2017 -495.48
- wusa        1   0.10040 4.3021 -494.06
- urals       1   0.12700 4.3287 -493.16
- tornetrask  1   0.13070 4.3324 -493.04
- jasper      1   0.26509 4.4668 -488.61
- tasman      1   0.45420 4.6559 -482.60

Step:  AIC=-497.43
nhtemp ~ wusa + jasper + chesapeake + tornetrask + urals + mongolia + 
    tasman

             Df Sum of Sq    RSS     AIC
- mongolia    1   0.02433 4.2276 -498.59
- chesapeake  1   0.03010 4.2334 -498.39
&lt;none&gt;                    4.2033 -497.43
- urals       1   0.12588 4.3292 -495.15
- tornetrask  1   0.17416 4.3775 -493.54
- wusa        1   0.17898 4.3823 -493.38
- jasper      1   0.27028 4.4736 -490.39
- tasman      1   0.46472 4.6680 -484.22

Step:  AIC=-498.59
nhtemp ~ wusa + jasper + chesapeake + tornetrask + urals + tasman

             Df Sum of Sq    RSS     AIC
&lt;none&gt;                    4.2276 -498.59
- chesapeake  1   0.08207 4.3097 -497.80
- urals       1   0.19293 4.4206 -494.12
- tornetrask  1   0.24611 4.4737 -492.38
- jasper      1   0.24694 4.4746 -492.36
- wusa        1   0.30524 4.5329 -490.48
- tasman      1   0.45557 4.6832 -485.75</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = nhtemp ~ wusa + jasper + chesapeake + tornetrask + 
    urals + tasman, data = globwarm1856)

Coefficients:
(Intercept)         wusa       jasper   chesapeake   tornetrask        urals  
   -0.25497      0.09703     -0.21360     -0.04788      0.10893      0.21017  
     tasman  
    0.11268  </code></pre>
</div>
</div>
<p>The <code>step()</code> function chooses the model with predictors <code>wusa</code>, <code>jasper</code>, <code>chesapeake</code>, <code>tornatrask</code>, <code>urals</code>, and <code>tasman</code> as the best model, eliminating <code>westgreen</code> and <code>mongolia</code>. Thus, observe the model chosen by stepwise elimination below.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = nhtemp ~ wusa + jasper + chesapeake + tornetrask + 
    urals + tasman, data = globwarm1856)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.41534 -0.10133  0.00671  0.09609  0.67544 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.25497    0.02149 -11.864  &lt; 2e-16 ***
wusa         0.09703    0.03074   3.157 0.001961 ** 
jasper      -0.21360    0.07523  -2.839 0.005207 ** 
chesapeake  -0.04788    0.02925  -1.637 0.103955    
tornetrask   0.10893    0.03843   2.834 0.005281 ** 
urals        0.21017    0.08375   2.509 0.013246 *  
tasman       0.11268    0.02922   3.856 0.000176 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.175 on 138 degrees of freedom
Multiple R-squared:  0.4732,    Adjusted R-squared:  0.4503 
F-statistic: 20.66 on 6 and 138 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Nearly all variables are significant. The multiple <span class="math inline">\(R^2\)</span> decreased from the full model, which makes sense, since <span class="math inline">\(R^2\)</span> “rewards” the addition of more variables — <span class="math inline">\(R^2=1-\frac{RSS}{TSS}\)</span>, and <span class="math inline">\(RSS\)</span> can only increase upon the inclusion of more variables. However, the adjusted <span class="math inline">\(R^2\)</span>, which is defined as <span class="math inline">\(R_a^2=1-\frac{\hat\sigma_{model}^2}{\hat\sigma_{null}^2}\)</span>, only increases if the inclusion of a variable increases the predictive value of the model. Thus, observing the adjusted <span class="math inline">\(R^2\)</span> of both models, one sees that it is higher in the model selected by stepwise elimination.</p>
</section>
<section id="box-cox-transformation" class="level2">
<h2 class="anchored" data-anchor-id="box-cox-transformation">4. Box-Cox Transformation</h2>
<p>To proceed building and evaluating models, it will be fruitful to evaluate the possible necessity for a transformation of the response variable, <code>nhtemp</code>. The method of evaluating possible transformations of the response is the Box-Cox transformation, which transforms a given response <span class="math inline">\(y\)</span> to one of the form <span class="math display">\[g_\lambda(y)=\begin{cases}y^\lambda &amp; \lambda \not = 0 \\ \log{y} &amp; \lambda=0\end{cases}\]</span> where <span class="math inline">\(\lambda\)</span> is estimated by maximum likelihood. Thus, if the 95% confidence interval of <span class="math inline">\(\lambda\)</span> includes 1, it is most likely that no transformation is necessary; otherwise, the expected value of <span class="math inline">\(\lambda\)</span> should be used to transform the response.</p>
<p>One crucial aspect of Box-Cox transformation is that it requires the response to take only positive values. To check that this assumption is met, one can get a summary of the variable <code>nhtemp</code> in <code>globwarm1856</code>.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
-0.6200 -0.2800 -0.1500 -0.1203  0.0300  0.6600 </code></pre>
</div>
</div>
<p>The summary reveals that a majority of the <code>nhtemp</code> data is negative, which makes sense in terms of what the data is actually communicating: in layman’s terms, this means that a majority of days in the northern hemisphere are below freezing (0º C). Since the minimum value of <code>nhtemp</code> is small in terms of absolute value, one can amend the negative values by scaling values by 1, which will modify the intercept term in the linear regression model but none of the other coefficents (since the general structure of the data is preserved).</p>
<p>Now there exists a variable <code>nhtemp_pos</code> which takes only positive values while maintaining the structure of the original response, <code>nhtemp</code>. This variable may thus be used instead of the original to test the need for a transformation via Box-Cox. The log-Likelihood function of <span class="math inline">\(\lambda\)</span> is plotted below, with the 95% confidence interval denoted with dashed lines.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SLMMidtermExam_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Notably, 1 is not within the 95% confidence interval for <span class="math inline">\(\lambda\)</span>, meaning a transformation of the response is necessary. I have chosen <span class="math inline">\(\lambda=0.25\)</span>, which seems close to the expected value of <span class="math inline">\(\lambda\)</span> (the middlemost vertical dashed line above).</p>
<p>To evaluate the efficacy of this transformation, one may build linear regression models that include the transformation and compare them to those that do not. Below are the models equivalent to the full model and stepwise elimination model introduced in the above subsection, with the transformation <span class="math inline">\(g(y)=y^{0.25}\)</span> applied to the response. Though not included in the output here, I have also updated the previous models to assign <code>nhtemp_pos</code> as the response — these models will be discussed in the Conclusion section. We look first at the summary of the full model with the Box-Cox transformation applied.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = I(nhtemp_pos^(0.25)) ~ wusa + jasper + westgreen + 
    chesapeake + tornetrask + urals + mongolia + tasman, data = globwarm1856)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.141734 -0.029997  0.001866  0.027110  0.147567 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.925782   0.007348 125.996  &lt; 2e-16 ***
wusa         0.023906   0.011677   2.047 0.042558 *  
jasper      -0.048674   0.021247  -2.291 0.023507 *  
westgreen    0.004431   0.011382   0.389 0.697643    
chesapeake  -0.007233   0.009263  -0.781 0.436242    
tornetrask   0.029749   0.012255   2.427 0.016514 *  
urals        0.036395   0.024871   1.463 0.145675    
mongolia     0.007818   0.012457   0.628 0.531292    
tasman       0.028598   0.008191   3.491 0.000648 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.04781 on 136 degrees of freedom
Multiple R-squared:  0.4805,    Adjusted R-squared:  0.4499 
F-statistic: 15.72 on 8 and 136 DF,  p-value: 3.055e-16</code></pre>
</div>
</div>
<p>Notice above that 4 of the 8 predictors are significant, the multiple <span class="math inline">\(R^2\)</span> has increased from the full model, the adjusted <span class="math inline">\(R^2\)</span> has increased as well, and, most importantly, the residual standard error has decreased significantly. Now, we look at the summary of the stepwise elimination model with the Box-Cox transformation applied.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = I(nhtemp_pos^(0.25)) ~ wusa + jasper + chesapeake + 
    tornetrask + urals + tasman, data = globwarm1856)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.144926 -0.029058  0.001823  0.026186  0.151504 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.922889   0.005838 158.097  &lt; 2e-16 ***
wusa         0.028913   0.008350   3.463 0.000712 ***
jasper      -0.046562   0.020436  -2.278 0.024237 *  
chesapeake  -0.010209   0.007946  -1.285 0.201036    
tornetrask   0.033753   0.010439   3.233 0.001531 ** 
urals        0.039463   0.022749   1.735 0.085029 .  
tasman       0.027687   0.007937   3.488 0.000653 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.04754 on 138 degrees of freedom
Multiple R-squared:  0.4787,    Adjusted R-squared:  0.4561 
F-statistic: 21.12 on 6 and 138 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Notice above that 4 of the 6 predictors are significant, the multiple <span class="math inline">\(R^2\)</span> has increased from the full model, the adjusted <span class="math inline">\(R^2\)</span> has increased as well, and, most importantly, the residual standard error has decreased significantly. Overall, both Box-Cox transformed models perform better or equivalently to the pre-transformation models on all fronts.</p>
</section>
<section id="parameter-estimates-and-standard-errors" class="level2">
<h2 class="anchored" data-anchor-id="parameter-estimates-and-standard-errors">5./6. Parameter Estimates and Standard Errors</h2>
<p>To view and compare the paramter (i.e., coefficient) estimates and their standard errors, one may use the function <code>compareCoefs()</code> from the <code>car</code> package. We do so below. The first two columns represent the pre-transformation models (full and stepwise elimination), while the second two represent the post-transformation models.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Calls:
1: lm(formula = nhtemp ~ wusa + jasper + westgreen + chesapeake + 
  tornetrask + urals + mongolia + tasman, data = globwarm1856)
2: lm(formula = nhtemp ~ wusa + jasper + chesapeake + tornetrask + urals + 
  tasman, data = globwarm1856)
3: lm(formula = I(nhtemp_pos^(0.25)) ~ wusa + jasper + westgreen + 
  chesapeake + tornetrask + urals + mongolia + tasman, data = globwarm1856)
4: lm(formula = I(nhtemp_pos^(0.25)) ~ wusa + jasper + chesapeake + 
  tornetrask + urals + tasman, data = globwarm1856)

             Model 1  Model 2  Model 3  Model 4
(Intercept) -0.24256 -0.25497  0.92578  0.92289
SE           0.02701  0.02149  0.00735  0.00584
                                               
wusa         0.07738  0.09703  0.02391  0.02891
SE           0.04293  0.03074  0.01168  0.00835
                                               
jasper       -0.2288  -0.2136  -0.0487  -0.0466
SE            0.0781   0.0752   0.0212   0.0204
                                               
westgreen    0.00958           0.00443         
SE           0.04184           0.01138         
                                               
chesapeake  -0.03211 -0.04788 -0.00723 -0.01021
SE           0.03405  0.02925  0.00926  0.00795
                                               
tornetrask    0.0927   0.1089   0.0297   0.0338
SE            0.0451   0.0384   0.0123   0.0104
                                               
urals         0.1854   0.2102   0.0364   0.0395
SE            0.0914   0.0837   0.0249   0.0227
                                               
mongolia     0.04197           0.00782         
SE           0.04579           0.01246         
                                               
tasman       0.11545  0.11268  0.02860  0.02769
SE           0.03011  0.02922  0.00819  0.00794
                                               </code></pre>
</div>
</div>
<p>The greatest variation in parameter between the models occurs in <code>(Intercept)</code>, which is to be expected since the Box-Cox evaluation required that the response be scaled by a constant. Otherwise, the parameters are either positive or negative across all four models, not a mix of the two. The parameter estimates of the non-transformed models tend to be more similar (in terms of absolute value) to each other than to the other models, and the same is true for the post-transformation models. Additionally, the standard error for each parameter decreases upon transformation of the response.</p>
<p>We can interpret the parameters contextually to provide further information about the nature of the model. To do so, let us look in particular at <code>Model 1</code> above, the full model. In general, to interpret these parameters, one must imagine a world in which all variables except the one in question are held constant; for example, if one were to examine the parameter for <code>mongolia</code>, they would have to imagine that the trees in the western United States, Canada, Sweden, the Urals, and Tasmania did not grow, that the ice core in west Greenland did not melt or freeze further, and that the seashells found in Chesapeake Bay did not change either. Parameters may only be interpreted in isolation if other variables are held constant.</p>
<p>Thus, if none of the climate proxy information changed between two subsequent years, then the average yearly temperature in the Northern Hemisphere would be expected to decrease by 0.24256 ºC (this corresponds to the <code>(Intercept)</code> term).</p>
<p>If only the tree ring proxy information from Western USA changed, then for every unit that it increased/decreased, the average yearly temperature would be expected to change in the same direction by 0.07738 ºC.</p>
<p>If only the tree ring proxy information from Canada changed, then for every unit that it increased/decreased, the average yearly temperature would be expected to change in the opposite direction by 0.2288 ºC.</p>
<p>If only the ice core proxy information from west Greenland changed, then for every unit that it increased/decreased, the average yearly temperature would be expected to change in the same direction by 0.00958 ºC.</p>
<p>If only the seashell proxy information from Chesapeake Bay changed, then for every unit that it increased/decreased, the average yearly temperature would be expected to change in the opposite direction by 0.03211 ºC.</p>
<p>If only the tree ring proxy information from Sweden changed, then for every unit that it increased/decreased, the average yearly temperature would be expected to change in the same direction by 0.0927 ºC.</p>
<p>If only the tree ring proxy information from the Urals changed, then for every unit that it increased/decreased, the average yearly temperature would be expected to change in the same direction by 0.1854 ºC.</p>
<p>If only the tree ring proxy information from Mongolia changed, then for every unit that it increased/decreased, the average yearly temperature would be expected to change in the same direction by 0.04197 ºC.</p>
<p>If only the tree ring proxy information from Tasmania changed, then for every unit that it increased/decreased, the average yearly temperature would be expected to change in the same direction by 0.11545 ºC.</p>
<p>A similar interpretation could be repeated for the other models above. However, these types of interpretations are not the most realistic for the given problem. In cases of experimental data, one has control over different factors and thus the “holding constant” of variables can have a tangible meaning. In cases of observational data, like <code>globwarm</code>, there is no such control over variables: it is impossible to stop a tree from growing for a year in the real world. Nevertheless, these interpretations do contribute to the understanding of the inner workings of the linear model, which can in turn give insights on the real world. For example, taking note of the fact that none of the parameters have an absolute value greater than 0.5, it can be stated that — in general — processes of climate change occur gradually, rather than rapidly.</p>
</section>
</section>
<section id="part-3" class="level1">
<h1>Part 3</h1>
<section id="regression-diagnostics" class="level2">
<h2 class="anchored" data-anchor-id="regression-diagnostics">7. Regression Diagnostics</h2>
<p>In building the above models, some assumptions have been invoked without testing their validity. In this section, the goal is to test whether or not (1) the residuals of the models have constant variance, and (2) whether the residuals of the models are normally distributed. To do so, I have written the following function. The function first produces a plot of residuals against fitted values to evaluate (1) and a Q-Q plot to test (2). Then, the function tests (1) using the non-constant variance test and (2) using the Shapiro-Wilks’ test of normality.</p>
<p>We begin by evaluating the validity of the assumptions on the full model.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SLMMidtermExam_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SLMMidtermExam_files/figure-html/unnamed-chunk-23-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Non-constant Variance Score Test 
Variance formula: ~ fitted.values 
Chisquare = 5.343177, Df = 1, p = 0.020804

    Shapiro-Wilk normality test

data:  resid(lm)
W = 0.97456, p-value = 0.00842</code></pre>
</div>
</div>
<p>There seem to be areas of the Residuals vs.&nbsp;Fitted plot where the residuals bunch closer to zero (e.g.&nbsp;the interval [-0.4,-0.3]), and areas with higher variance (e.g.&nbsp;the interval [-0.1,0]). Furthermore, the rightmost tail of the Q-Q plot data trails far away from the line <span class="math inline">\(y=x\)</span>. This leads me to believe that neither of the assumptions are met, which is confirmed by the small <span class="math inline">\(p\)</span>-values present in the nonconstant variance and Shapiro-Wilks’ tests. These small <span class="math inline">\(p\)</span>-values indicate that the null hypotheses should be rejected, which correspond to homoskedasticity and normality, respectively. In other words, this model’s residuals are heterskedastic and non-normal.</p>
<p>Now, we look at the stepwise elimination model.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SLMMidtermExam_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SLMMidtermExam_files/figure-html/unnamed-chunk-24-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Non-constant Variance Score Test 
Variance formula: ~ fitted.values 
Chisquare = 3.755518, Df = 1, p = 0.052633

    Shapiro-Wilk normality test

data:  resid(lm)
W = 0.96745, p-value = 0.001601</code></pre>
</div>
</div>
<p>There is less of an issue with “bunching” than in the previous model, with some instances of much greater variance (e.g.&nbsp;[-0.1,0]). The rightmost tail again trails far from the line <span class="math inline">\(y=x\)</span>, indicating non-normality. The nonconstant variance test returns a <span class="math inline">\(p\)</span>-value just above 0.05, meaning the null is not rejected, but the Shapiro-Wilks’ test returns <span class="math inline">\(p&lt;0.05\)</span>, meaning the residuals are not normally distributed. Thus, the assumptions are not met by the stepwise elimination model either.</p>
<p>Now we observe the full model with the response transformed via Box-Cox.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SLMMidtermExam_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SLMMidtermExam_files/figure-html/unnamed-chunk-25-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Non-constant Variance Score Test 
Variance formula: ~ fitted.values 
Chisquare = 0.003355372, Df = 1, p = 0.95381

    Shapiro-Wilk normality test

data:  resid(lm)
W = 0.98782, p-value = 0.2349</code></pre>
</div>
</div>
<p>Looking at the vertical axes of both plots, we note that they are on a notably smaller order of magnitude than the above two models’ were. Thus, though the shape of the Residuals vs.&nbsp;Fitted plot appears similar, the variance of the residuals is actually closer to constant. Similarly, the rightmost tail of the Q-Q plot does not trail nearly as much as in the two previous examples. Thus, it seems that the assumptions are met. This is confirmed by the two tests, both of which return <span class="math inline">\(p&gt;0.05\)</span>, meaning we fail to reject the null in both cases. Therefore, the Box-Cox transformation model with all predictors meets the assumptions.</p>
<p>We turn our attention now to the Box-Cox transformed model with predictors chosen by stepwise elimination.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SLMMidtermExam_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SLMMidtermExam_files/figure-html/unnamed-chunk-26-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Non-constant Variance Score Test 
Variance formula: ~ fitted.values 
Chisquare = 0.01402778, Df = 1, p = 0.90572

    Shapiro-Wilk normality test

data:  resid(lm)
W = 0.98568, p-value = 0.1378</code></pre>
</div>
</div>
<p>Just as above, the vertical axes are on a smaller order of magnitude than the first two models, so the variation in the Residuals vs.&nbsp;Fitted plot is smaller and the tail of the Q-Q plots travels less far away from the line <span class="math inline">\(y=\)</span>. The hypothesis tests again confirm that the assumptions are met.</p>
<p>Thus, overall, the Box-Cox transformed models meet the assumptions of linear regression, while the ones without the transformation do not.</p>
</section>
<section id="unusual-observations" class="level2">
<h2 class="anchored" data-anchor-id="unusual-observations">8. Unusual Observations</h2>
<p>Certain observations can drastically affect the fit of a linear model. Such observations, termed “influential points,” may be found via a series of heuristics regarding the “distance” of an observation from its fitted value. I have written the following function to streamline finding influential points. First, it finds all points with large leverage, which are generally defined as those points which have a high impact in the fitting of a linear model. Heuristically, they are defined as those whose leverage are more than twice the mean of the hat values (recalling that the hat values are the diagonals of <span class="math inline">\(H=X(X^TX)^{-1}X^T\)</span>). Then, it finds all outlier data, which are points that do not fit the model well, heuristically defined as those points whose standardized residuals are greater than 2 or less than -2. Finally, it checks all of these points to find the influential points, heuristically defined as those points whose Cook’s distance (<span class="math inline">\(D_i=\frac{1}{p}r_i^2\frac{h_i}{1-h_i}\)</span>, a function of both leverage and standardized residuals) is greater than <span class="math inline">\(\frac{4}{n}\)</span>, where <span class="math inline">\(n\)</span> is the sample size.</p>
<p>To observe the effect of influential points on the models, let us look at the model with the worst fit (the full model with not transformation) and the model with the best fit (the transformed model with predictors selected via stepwise transformation).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Large Leverage"
named numeric(0)
[1] "Outliers"
     1862      1878      1917      1918      1995      1997      1998      1999 
-2.264011  2.253758 -2.570472 -2.038099  2.473404  2.652667  3.841535  2.746664 
     2000 
 2.446509 
[1] "Influential Points"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>1862 1878 1917 1918 1995 1997 1998 1999 2000 
TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE </code></pre>
</div>
</div>
<p>Thus, the influential points in the original model are the observations associated with the years 1862, 1878, 1917, 1918, 1995, 1997, 1998, 1999, and 2000. We check the same for the best model.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Large Leverage"
named numeric(0)
[1] "Outliers"
     1862      1878      1917      1995      1997      1998      1999      2000 
-3.116175  2.280661 -2.723746  2.149998  2.423217  3.260177  2.571606  2.363861 
[1] "Influential Points"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> 1862  1878  1917  1995  1997  1998  1999  2000 
 TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE </code></pre>
</div>
</div>
<p>The influential points for the transformed stepwise elimination model are nearly the same as for the original, full model: 1862, 1878, 1917, 1995, 1997, 1998, 1999, and 2000. We thus see that choice of model does not have a great impact on the set of influential points. Furthermore, it is notable that the majority of influential points are from the last 10 years of the dataset; in other words, this inspection could be used as evidence that the environmental impact of modern technology is affecting global temperatures in profound ways.</p>
<p>For prediction purposes, we create a new dataset excluding the influential points.</p>
<p>Additionally, we refit the full model using this smaller dataset.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = nhtemp_pos ~ wusa + jasper + westgreen + chesapeake + 
    tornetrask + urals + mongolia + tasman, data = globwarm1856_clean)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.26803 -0.08915 -0.00028  0.09221  0.32473 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.712301   0.021475  33.168  &lt; 2e-16 ***
wusa         0.124087   0.033424   3.713 0.000306 ***
jasper      -0.111048   0.059732  -1.859 0.065328 .  
westgreen   -0.001757   0.031646  -0.056 0.955818    
chesapeake  -0.074221   0.026616  -2.789 0.006109 ** 
tornetrask   0.192578   0.036680   5.250  6.2e-07 ***
urals        0.026577   0.072313   0.368 0.713841    
mongolia    -0.051917   0.036165  -1.436 0.153589    
tasman       0.059068   0.024097   2.451 0.015594 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1301 on 127 degrees of freedom
Multiple R-squared:  0.6041,    Adjusted R-squared:  0.5792 
F-statistic: 24.23 on 8 and 127 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Both the <span class="math inline">\(R^2\)</span> and adjusted <span class="math inline">\(R^2\)</span> have increased from the full model, and the residual standard error has decreased. The number of significant predictors is constant between the two. To further demonstrate the improvement this has caused, let us rerun the diagnostic analysis.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SLMMidtermExam_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SLMMidtermExam_files/figure-html/unnamed-chunk-32-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Non-constant Variance Score Test 
Variance formula: ~ fitted.values 
Chisquare = 1.514217, Df = 1, p = 0.2185

    Shapiro-Wilk normality test

data:  resid(lm)
W = 0.99005, p-value = 0.444</code></pre>
</div>
</div>
<p>The problems present earlier in the plots, as well as the small <span class="math inline">\(p\)</span>-values in the nonconstant variance and Shapiro-Wilks’ tests, are all resolved. In other words, the removal of influential points allowed the original model to meet the assumptions that it previously failed to meet.</p>
</section>
<section id="collinearity" class="level2">
<h2 class="anchored" data-anchor-id="collinearity">9. Collinearity</h2>
<p>Though collinearity does not affect the predictive power of a linear regression model, it does affect the ability to discern effects of specific predictor variables on the response. Thus, though the main aim of this analysis is to predict values of <code>nhtemp</code>, it can also be useful to evaluate collinearity to understand the interaction between temperature and each of the climate proxies. In short, collinearity can cause instability of the parameter estimates <span class="math inline">\(\hat\beta\)</span>.</p>
<p>Collinearity is the phenomenon in which there exists a (usually imperfect) linear relationship between some set of predictor variables. To determine the existence of collinearity, one may calculate the condition numbers <span class="math inline">\(\kappa_i\)</span> of the eigenvalues of the model matrix <span class="math inline">\(X\)</span>, which denote the relative size of the eigenvalues, or one may calculate the variance inflation factors (VIF) of the parameters of the model, which are large when the variance of its corresponding parameter, <span class="math inline">\(\textrm{var}\hat\beta_j\)</span>, is large.</p>
<p>I have written the following function to calculate and display the condition numbers of a given linear model.</p>
<p>We check the condition numbers of the full model as well as the stepwise elimination model (the “worst” and “best” models in terms of fit) in order to see if the removal of some predictors aided or worsened collinearity.</p>
<div class="cell">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-84cb1200{}.cl-84c916a8{font-family:'Arial';font-size:10pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-84c916a9{font-family:'Arial';font-size:10pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-84c9e45c{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-84c9ed44{width:1.019in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84c9ed45{width:1.496in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84c9ed46{width:1.019in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84c9ed4e{width:1.496in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84c9ed4f{width:1.019in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84c9ed50{width:1.496in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84c9ed51{width:1.019in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84c9ed52{width:1.496in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-84cb1200"><thead><tr style="overflow-wrap:break-word;"><th class="cl-84c9ed44"><p class="cl-84c9e45c"><span class="cl-84c916a8">Eigenvalue</span></p></th><th class="cl-84c9ed45"><p class="cl-84c9e45c"><span class="cl-84c916a8">Condition.Number</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-84c9ed46"><p class="cl-84c9e45c"><span class="cl-84c916a9">467.756817</span></p></td><td class="cl-84c9ed4e"><p class="cl-84c9e45c"><span class="cl-84c916a9">1.000000</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-84c9ed4f"><p class="cl-84c9e45c"><span class="cl-84c916a9">76.137442</span></p></td><td class="cl-84c9ed50"><p class="cl-84c9e45c"><span class="cl-84c916a9">2.478626</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-84c9ed4f"><p class="cl-84c9e45c"><span class="cl-84c916a9">52.512153</span></p></td><td class="cl-84c9ed50"><p class="cl-84c9e45c"><span class="cl-84c916a9">2.984559</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-84c9ed4f"><p class="cl-84c9e45c"><span class="cl-84c916a9">44.468188</span></p></td><td class="cl-84c9ed50"><p class="cl-84c9e45c"><span class="cl-84c916a9">3.243287</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-84c9ed4f"><p class="cl-84c9e45c"><span class="cl-84c916a9">22.885193</span></p></td><td class="cl-84c9ed50"><p class="cl-84c9e45c"><span class="cl-84c916a9">4.520982</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-84c9ed4f"><p class="cl-84c9e45c"><span class="cl-84c916a9">11.231025</span></p></td><td class="cl-84c9ed50"><p class="cl-84c9e45c"><span class="cl-84c916a9">6.453575</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-84c9ed4f"><p class="cl-84c9e45c"><span class="cl-84c916a9">4.736246</span></p></td><td class="cl-84c9ed50"><p class="cl-84c9e45c"><span class="cl-84c916a9">9.937861</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-84c9ed51"><p class="cl-84c9e45c"><span class="cl-84c916a9">3.198537</span></p></td><td class="cl-84c9ed52"><p class="cl-84c9e45c"><span class="cl-84c916a9">12.093009</span></p></td></tr></tbody></table></div>
</div>
<div class="cell-output-display">
<div class="tabwid"><style>.cl-84d1b222{}.cl-84cfabee{font-family:'Arial';font-size:10pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-84cfabf8{font-family:'Arial';font-size:10pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-84d083de{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-84d08c58{width:1.019in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84d08c59{width:1.496in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84d08c62{width:1.019in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84d08c63{width:1.496in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84d08c64{width:1.019in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84d08c65{width:1.496in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-84d1b222"><thead><tr style="overflow-wrap:break-word;"><th class="cl-84d08c58"><p class="cl-84d083de"><span class="cl-84cfabee">Eigenvalue</span></p></th><th class="cl-84d08c59"><p class="cl-84d083de"><span class="cl-84cfabee">Condition.Number</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-84d08c62"><p class="cl-84d083de"><span class="cl-84cfabf8">303.835995</span></p></td><td class="cl-84d08c63"><p class="cl-84d083de"><span class="cl-84cfabf8">1.000000</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-84d08c62"><p class="cl-84d083de"><span class="cl-84cfabf8">63.676924</span></p></td><td class="cl-84d08c63"><p class="cl-84d083de"><span class="cl-84cfabf8">2.184382</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-84d08c62"><p class="cl-84d083de"><span class="cl-84cfabf8">52.139306</span></p></td><td class="cl-84d08c63"><p class="cl-84d083de"><span class="cl-84cfabf8">2.413998</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-84d08c62"><p class="cl-84d083de"><span class="cl-84cfabf8">38.845297</span></p></td><td class="cl-84d08c63"><p class="cl-84d083de"><span class="cl-84cfabf8">2.796729</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-84d08c62"><p class="cl-84d083de"><span class="cl-84cfabf8">5.525562</span></p></td><td class="cl-84d08c63"><p class="cl-84d083de"><span class="cl-84cfabf8">7.415345</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-84d08c64"><p class="cl-84d083de"><span class="cl-84cfabf8">3.430116</span></p></td><td class="cl-84d08c65"><p class="cl-84d083de"><span class="cl-84cfabf8">9.411638</span></p></td></tr></tbody></table></div>
</div>
</div>
<p>Large condition numbers are a sign of collinearity. Condition numbers are considered large when <span class="math inline">\(\kappa_i\geq30\)</span>. The largest condition number above, <span class="math inline">\(\kappa=12.093009\)</span> is less than 30, meaning the method of condition numbers does not indicate the presence of collinearity. Now, we check the variance inflation factors of the full model as well as the stepwise elimination model, in the same manner as above.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      wusa     jasper  westgreen chesapeake tornetrask      urals   mongolia 
  5.229919   5.955474   1.782338   1.978483   4.696358   6.736267  10.187902 
    tasman 
  1.635938 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>      wusa     jasper chesapeake tornetrask      urals     tasman 
  2.704498   5.572285   1.472545   3.446143   5.700140   1.553624 </code></pre>
</div>
</div>
<p>A variance inflation factor of 1 indicates completely orthogonal variables; the further a VIF is from 1, the greater an impact collinearity has on the instability of the model. In the larger model, there are some relatively large VIFs, namely, <code>wusa</code>, <code>jasper</code>, <code>urals</code>, and <code>mongolia</code>. The first three of these predictors’ VIFs decrease upon the removal of some predictors, while the final one is itself removed. To see the effect of the removal of some predictors, observe that the standard error for <code>wusa</code> in the full model is <span class="math inline">\(\sqrt{5.229919}=2.286902\)</span> times larger than it would be without collinearity, while in the smaller model, this is reduced to <span class="math inline">\(\sqrt{2.704498}=1.644536\)</span>.</p>
<p>Overall, none of the condition numbers or VIFs are large enough to indicate a concerning amount of collinearity.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>Over the course of the analysis, seven different linear regression models were built over the course of this report. A table including the <span class="math inline">\(R^2\)</span>, adjusted <span class="math inline">\(R^2\)</span>, and residual standard error (RSE) for each model is included below. The Scaled Response Models refer to the models with <code>nhtemp_pos = nhtemp + 1</code> as the response variable. Note that the values in the table are exactly equal between the Scaled Response models and their equivalent original models.</p>
<div class="cell">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-84d8e722{}.cl-84d690ee{font-family:'Arial';font-size:10pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-84d690f8{font-family:'Arial';font-size:10pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-84d758a8{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-84d758a9{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-84d76212{width:2in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84d7621c{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 1.5pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84d7621d{width:2in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84d7621e{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84d76226{width:2in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84d76227{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-84d8e722"><thead><tr style="overflow-wrap:break-word;"><th class="cl-84d76212"><p class="cl-84d758a8"><span class="cl-84d690ee">Model</span></p></th><th class="cl-84d7621c"><p class="cl-84d758a9"><span class="cl-84d690ee">R.Sq</span></p></th><th class="cl-84d7621c"><p class="cl-84d758a9"><span class="cl-84d690ee">Adj.R.Sq</span></p></th><th class="cl-84d7621c"><p class="cl-84d758a9"><span class="cl-84d690ee">RSE</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-84d7621d"><p class="cl-84d758a8"><span class="cl-84d690f8">Full Model</span></p></td><td class="cl-84d7621e"><p class="cl-84d758a9"><span class="cl-84d690f8">0.4764458</span></p></td><td class="cl-84d7621e"><p class="cl-84d758a9"><span class="cl-84d690f8">0.4456485</span></p></td><td class="cl-84d7621e"><p class="cl-84d758a9"><span class="cl-84d690f8">0.17576870</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-84d7621d"><p class="cl-84d758a8"><span class="cl-84d690f8">Stepwise Elimination</span></p></td><td class="cl-84d7621e"><p class="cl-84d758a9"><span class="cl-84d690f8">0.4732116</span></p></td><td class="cl-84d7621e"><p class="cl-84d758a9"><span class="cl-84d690f8">0.4503078</span></p></td><td class="cl-84d7621e"><p class="cl-84d758a9"><span class="cl-84d690f8">0.17502848</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-84d7621d"><p class="cl-84d758a8"><span class="cl-84d690f8">Scaled Response Model (all predictors)</span></p></td><td class="cl-84d7621e"><p class="cl-84d758a9"><span class="cl-84d690f8">0.4764458</span></p></td><td class="cl-84d7621e"><p class="cl-84d758a9"><span class="cl-84d690f8">0.4456485</span></p></td><td class="cl-84d7621e"><p class="cl-84d758a9"><span class="cl-84d690f8">0.17576870</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-84d7621d"><p class="cl-84d758a8"><span class="cl-84d690f8">Scaled Response Model (stepwise predictors only)</span></p></td><td class="cl-84d7621e"><p class="cl-84d758a9"><span class="cl-84d690f8">0.4732116</span></p></td><td class="cl-84d7621e"><p class="cl-84d758a9"><span class="cl-84d690f8">0.4503078</span></p></td><td class="cl-84d7621e"><p class="cl-84d758a9"><span class="cl-84d690f8">0.17502848</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-84d7621d"><p class="cl-84d758a8"><span class="cl-84d690f8">Box-Cox Transformation (all predictors)</span></p></td><td class="cl-84d7621e"><p class="cl-84d758a9"><span class="cl-84d690f8">0.4804547</span></p></td><td class="cl-84d7621e"><p class="cl-84d758a9"><span class="cl-84d690f8">0.4498932</span></p></td><td class="cl-84d7621e"><p class="cl-84d758a9"><span class="cl-84d690f8">0.04781295</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-84d7621d"><p class="cl-84d758a8"><span class="cl-84d690f8">Box-Cox Transformation (stepwise predictors only)</span></p></td><td class="cl-84d7621e"><p class="cl-84d758a9"><span class="cl-84d690f8">0.4787366</span></p></td><td class="cl-84d7621e"><p class="cl-84d758a9"><span class="cl-84d690f8">0.4560730</span></p></td><td class="cl-84d7621e"><p class="cl-84d758a9"><span class="cl-84d690f8">0.04754363</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-84d76226"><p class="cl-84d758a8"><span class="cl-84d690f8">Full Model (no influential points)</span></p></td><td class="cl-84d76227"><p class="cl-84d758a9"><span class="cl-84d690f8">0.6041268</span></p></td><td class="cl-84d76227"><p class="cl-84d758a9"><span class="cl-84d690f8">0.5791899</span></p></td><td class="cl-84d76227"><p class="cl-84d758a9"><span class="cl-84d690f8">0.13008004</span></p></td></tr></tbody></table></div>
</div>
</div>
<p>Based solely on the information in the above table, one could choose from several “best” models. The full model which excludes influential points has the highest <span class="math inline">\(R^2\)</span> and adjusted <span class="math inline">\(R^2\)</span>, and, as shown above, meets all of the assumptions. However, this model there are models with lower residual standard error, and the fact that it relies on all predictors means it is more expensive in terms of data collection. Thus, I would nominate the Box-Cox transformed stepwise elimination model as the “best” model, given that it has fewer predictors, minimal residual standard error, and the second-highest adjusted <span class="math inline">\(R^2\)</span> of all the models in this report. This model also fits the assumptions.</p>
<p>The worst model would necessarily be the original, full model, which has minimal <span class="math inline">\(R^2\)</span> and adjusted <span class="math inline">\(R^2\)</span>, maximal residual standard error, and does not meet the necessary assumptions. It is furthermore expensive from a data collection standpoint since it requires all eight predictors.</p>
<p>In general, the major drawback of all of the above models is their lack of simple interpretability. Since the data is observational and not experimental, the metaphor of holding variables constant to simulate a simple linear regression is impossible to achieve in practice. Thus, while the transformed stepwise elimination model has good predictive capabilities, it does not have excellent explanatory power.</p>
<p>With all that in mind, I will predict the average temperature in the northern hemisphere in the years 1850 and 1000.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>           fit       lwr       upr
1850 0.8902689 0.7940665 0.9864712</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>           fit       lwr       upr
1000 0.8609581 0.7427095 0.9792068</code></pre>
</div>
</div>
<p>The confidence interval is smaller for the year closer to the known dataset than the year further from it. This tracks with what is generally known about the predictive ability of linear models.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>